local _, addonTable = ...

-- Benchmark boss splits for PeaversSplits.
--
-- A SPLIT is the time from the start of a keystone run to a boss dying. For
-- each dungeon and each exact keystone level this holds what the middle of
-- the pool does at every boss, so a running key can be told how far ahead or
-- behind it is while there is still something to do about it.
--
-- Schema:
--   updated   = "YYYY-MM-DD HH:MM:SS" (UTC)
--   partition = the game patch these pools were built on, "major.minor"
--   dungeons  = [mapChallengeModeID].levels[keystoneLevel][DungeonEncounterID]
--             = { order, name, split, fast, slow, runs }
--
-- `split` is the pool's median, `fast`/`slow` its p25/p75, all in SECONDS
-- from the start of the run. `runs` is the sample the figures rest on and is
-- per boss, not per level: a depleted run that ended at the third boss counts
-- toward the first two and not the last.
--
-- EXACT keystone level, never a band. Enemy health scales per level, so a
-- +19 is genuinely slower than a +10 for reasons that are not the group's
-- doing, and a level with no entry means no pool cleared the sample floor -
-- not that the run cannot be measured. Consumers must say so rather than
-- reaching for a neighbouring level.
--
-- ONE PARTITION ONLY. Every dungeon here was keyed on the same patch, so
-- nothing in this file can be compared against a pool from another one. A
-- dungeon rotated out of the current season simply has no entry.
--
-- Auto-generated by splits-module (PeaversAddonDataSupplier) from
-- parses.gg /api/keys/{id}/splits. Do not edit by hand.
addonTable.SplitsData = {
	updated = "2026-10-09 05:00:46",
	partition = "12.1",

	dungeons = {
		[249] = {
			name = "Kings' Rest",
			levels = {
				[5] = {
					[2139] = { order = 1, name = "The Golden Serpent", split = 302.7, fast = 264.3, slow = 321.3, runs = 6 },
					[2142] = { order = 2, name = "Mchimba the Embalmer", split = 777.2, fast = 710.8, slow = 804.3, runs = 6 },
					[2140] = { order = 3, name = "The Council of Tribes", split = 1135.2, fast = 990.4, slow = 1199.9, runs = 6 },
					[2143] = { order = 4, name = "Dazar, The First King", split = 1370.8, fast = 1244.2, slow = 1423.2, runs = 6 },
				},
				[6] = {
					[2139] = { order = 1, name = "The Golden Serpent", split = 272.6, fast = 266.3, slow = 304.8, runs = 5 },
					[2142] = { order = 2, name = "Mchimba the Embalmer", split = 776.6, fast = 725.6, slow = 913.8, runs = 5 },
					[2140] = { order = 3, name = "The Council of Tribes", split = 1058.7, fast = 1009.5, slow = 1336.0, runs = 5 },
					[2143] = { order = 4, name = "Dazar, The First King", split = 1259.2, fast = 1233.7, slow = 1557.7, runs = 5 },
				},
				[7] = {
					[2139] = { order = 1, name = "The Golden Serpent", split = 315.0, fast = 302.9, slow = 351.9, runs = 14 },
					[2142] = { order = 2, name = "Mchimba the Embalmer", split = 910.8, fast = 793.9, slow = 959.4, runs = 14 },
					[2140] = { order = 3, name = "The Council of Tribes", split = 1265.2, fast = 1139.5, slow = 1321.0, runs = 14 },
					[2143] = { order = 4, name = "Dazar, The First King", split = 1531.3, fast = 1355.7, slow = 1602.1, runs = 14 },
				},
				[8] = {
					[2139] = { order = 1, name = "The Golden Serpent", split = 311.7, fast = 280.5, slow = 348.4, runs = 10 },
					[2142] = { order = 2, name = "Mchimba the Embalmer", split = 800.8, fast = 783.7, slow = 930.2, runs = 10 },
					[2140] = { order = 3, name = "The Council of Tribes", split = 1128.9, fast = 1100.3, slow = 1306.2, runs = 10 },
					[2143] = { order = 4, name = "Dazar, The First King", split = 1334.8, fast = 1326.5, slow = 1532.7, runs = 10 },
				},
				[9] = {
					[2139] = { order = 1, name = "The Golden Serpent", split = 393.8, fast = 356.6, slow = 439.4, runs = 10 },
					[2142] = { order = 2, name = "Mchimba the Embalmer", split = 967.4, fast = 946.6, slow = 1023.7, runs = 10 },
					[2140] = { order = 3, name = "The Council of Tribes", split = 1359.2, fast = 1329.2, slow = 1428.4, runs = 10 },
					[2143] = { order = 4, name = "Dazar, The First King", split = 1602.6, fast = 1588.1, slow = 1684.3, runs = 10 },
				},
				[10] = {
					[2139] = { order = 1, name = "The Golden Serpent", split = 359.6, fast = 312.9, slow = 393.1, runs = 68 },
					[2142] = { order = 2, name = "Mchimba the Embalmer", split = 901.9, fast = 827.3, slow = 1010.3, runs = 69 },
					[2140] = { order = 3, name = "The Council of Tribes", split = 1278.6, fast = 1169.1, slow = 1424.9, runs = 69 },
					[2143] = { order = 4, name = "Dazar, The First King", split = 1538.9, fast = 1406.8, slow = 1743.2, runs = 69 },
				},
				[11] = {
					[2139] = { order = 1, name = "The Golden Serpent", split = 377.2, fast = 346.2, slow = 419.5, runs = 26 },
					[2142] = { order = 2, name = "Mchimba the Embalmer", split = 927.0, fast = 852.6, slow = 1021.9, runs = 26 },
					[2140] = { order = 3, name = "The Council of Tribes", split = 1325.6, fast = 1219.7, slow = 1464.2, runs = 26 },
					[2143] = { order = 4, name = "Dazar, The First King", split = 1629.5, fast = 1461.8, slow = 1766.3, runs = 26 },
				},
				[12] = {
					[2139] = { order = 1, name = "The Golden Serpent", split = 377.7, fast = 338.3, slow = 404.2, runs = 45 },
					[2142] = { order = 2, name = "Mchimba the Embalmer", split = 967.6, fast = 903.3, slow = 1022.0, runs = 46 },
					[2140] = { order = 3, name = "The Council of Tribes", split = 1368.1, fast = 1291.1, slow = 1485.8, runs = 46 },
					[2143] = { order = 4, name = "Dazar, The First King", split = 1647.7, fast = 1558.0, slow = 1785.9, runs = 46 },
				},
				[13] = {
					[2139] = { order = 1, name = "The Golden Serpent", split = 375.4, fast = 346.9, slow = 389.4, runs = 13 },
					[2142] = { order = 2, name = "Mchimba the Embalmer", split = 994.5, fast = 946.5, slow = 1026.8, runs = 13 },
					[2140] = { order = 3, name = "The Council of Tribes", split = 1427.8, fast = 1369.3, slow = 1480.8, runs = 13 },
					[2143] = { order = 4, name = "Dazar, The First King", split = 1740.6, fast = 1642.5, slow = 1830.1, runs = 13 },
				},
				[14] = {
					[2139] = { order = 1, name = "The Golden Serpent", split = 376.7, fast = 355.2, slow = 391.1, runs = 12 },
					[2142] = { order = 2, name = "Mchimba the Embalmer", split = 1015.3, fast = 929.0, slow = 1065.3, runs = 12 },
					[2140] = { order = 3, name = "The Council of Tribes", split = 1480.6, fast = 1359.3, slow = 1539.8, runs = 13 },
					[2143] = { order = 4, name = "Dazar, The First King", split = 1760.4, fast = 1646.0, slow = 1842.3, runs = 13 },
				},
				[15] = {
					[2139] = { order = 1, name = "The Golden Serpent", split = 379.5, fast = 373.7, slow = 422.0, runs = 14 },
					[2142] = { order = 2, name = "Mchimba the Embalmer", split = 1057.5, fast = 998.9, slow = 1086.2, runs = 14 },
					[2140] = { order = 3, name = "The Council of Tribes", split = 1497.8, fast = 1460.1, slow = 1552.0, runs = 14 },
					[2143] = { order = 4, name = "Dazar, The First King", split = 1825.6, fast = 1773.4, slow = 1871.0, runs = 14 },
				},
				[16] = {
					[2139] = { order = 1, name = "The Golden Serpent", split = 406.3, fast = 393.5, slow = 417.5, runs = 6 },
					[2142] = { order = 2, name = "Mchimba the Embalmer", split = 1060.7, fast = 1038.4, slow = 1105.5, runs = 6 },
					[2140] = { order = 3, name = "The Council of Tribes", split = 1573.5, fast = 1496.0, slow = 1758.0, runs = 6 },
					[2143] = { order = 4, name = "Dazar, The First King", split = 1879.1, fast = 1782.4, slow = 2122.2, runs = 6 },
				},
			},
		},
		[250] = {
			name = "Temple of Sethraliss",
			levels = {
				[2] = {
					[2124] = { order = 1, name = "Adderis and Aspix", split = 225.7, fast = 199.3, slow = 246.8, runs = 8 },
					[2125] = { order = 2, name = "Merektha", split = 596.0, fast = 474.4, slow = 619.1, runs = 8 },
					[2126] = { order = 3, name = "Galvazzt", split = 820.3, fast = 690.4, slow = 865.1, runs = 8 },
					[2127] = { order = 4, name = "Avatar of Sethraliss", split = 1204.2, fast = 1080.4, slow = 1247.0, runs = 8 },
				},
				[6] = {
					[2124] = { order = 1, name = "Adderis and Aspix", split = 247.8, fast = 216.4, slow = 265.7, runs = 6 },
					[2125] = { order = 2, name = "Merektha", split = 645.5, fast = 514.3, slow = 731.4, runs = 6 },
					[2126] = { order = 3, name = "Galvazzt", split = 862.1, fast = 706.9, slow = 977.0, runs = 6 },
					[2127] = { order = 4, name = "Avatar of Sethraliss", split = 1373.3, fast = 1249.0, slow = 1669.2, runs = 6 },
				},
				[7] = {
					[2124] = { order = 1, name = "Adderis and Aspix", split = 300.4, fast = 254.6, slow = 346.5, runs = 8 },
					[2125] = { order = 2, name = "Merektha", split = 740.4, fast = 693.8, slow = 876.6, runs = 8 },
					[2126] = { order = 3, name = "Galvazzt", split = 1046.2, fast = 972.1, slow = 1185.3, runs = 8 },
					[2127] = { order = 4, name = "Avatar of Sethraliss", split = 1692.5, fast = 1467.5, slow = 1768.8, runs = 8 },
				},
				[8] = {
					[2124] = { order = 1, name = "Adderis and Aspix", split = 257.8, fast = 253.2, slow = 262.5, runs = 6 },
					[2125] = { order = 2, name = "Merektha", split = 647.1, fast = 607.0, slow = 676.0, runs = 6 },
					[2126] = { order = 3, name = "Galvazzt", split = 891.3, fast = 844.6, slow = 944.2, runs = 6 },
					[2127] = { order = 4, name = "Avatar of Sethraliss", split = 1348.3, fast = 1280.5, slow = 1391.6, runs = 6 },
				},
				[9] = {
					[2124] = { order = 1, name = "Adderis and Aspix", split = 288.3, fast = 275.5, slow = 316.3, runs = 15 },
					[2125] = { order = 2, name = "Merektha", split = 755.2, fast = 713.3, slow = 795.7, runs = 15 },
					[2126] = { order = 3, name = "Galvazzt", split = 1063.1, fast = 985.8, slow = 1118.1, runs = 15 },
					[2127] = { order = 4, name = "Avatar of Sethraliss", split = 1568.4, fast = 1486.2, slow = 1611.4, runs = 15 },
				},
				[10] = {
					[2124] = { order = 1, name = "Adderis and Aspix", split = 298.3, fast = 264.1, slow = 332.4, runs = 77 },
					[2125] = { order = 2, name = "Merektha", split = 778.4, fast = 665.7, slow = 866.3, runs = 77 },
					[2126] = { order = 3, name = "Galvazzt", split = 1079.8, fast = 939.8, slow = 1187.4, runs = 77 },
					[2127] = { order = 4, name = "Avatar of Sethraliss", split = 1562.4, fast = 1378.4, slow = 1722.1, runs = 77 },
				},
				[11] = {
					[2124] = { order = 1, name = "Adderis and Aspix", split = 299.1, fast = 286.0, slow = 314.7, runs = 20 },
					[2125] = { order = 2, name = "Merektha", split = 798.6, fast = 750.7, slow = 872.5, runs = 20 },
					[2126] = { order = 3, name = "Galvazzt", split = 1117.7, fast = 1048.4, slow = 1236.5, runs = 20 },
					[2127] = { order = 4, name = "Avatar of Sethraliss", split = 1581.2, fast = 1473.1, slow = 1729.6, runs = 20 },
				},
				[12] = {
					[2124] = { order = 1, name = "Adderis and Aspix", split = 297.1, fast = 275.6, slow = 321.4, runs = 45 },
					[2125] = { order = 2, name = "Merektha", split = 762.9, fast = 732.3, slow = 828.5, runs = 45 },
					[2126] = { order = 3, name = "Galvazzt", split = 1068.7, fast = 1027.6, slow = 1174.2, runs = 45 },
					[2127] = { order = 4, name = "Avatar of Sethraliss", split = 1566.0, fast = 1466.0, slow = 1668.1, runs = 45 },
				},
				[13] = {
					[2124] = { order = 1, name = "Adderis and Aspix", split = 307.6, fast = 289.5, slow = 334.8, runs = 18 },
					[2125] = { order = 2, name = "Merektha", split = 795.6, fast = 765.1, slow = 858.4, runs = 19 },
					[2126] = { order = 3, name = "Galvazzt", split = 1126.1, fast = 1082.8, slow = 1224.3, runs = 19 },
					[2127] = { order = 4, name = "Avatar of Sethraliss", split = 1608.5, fast = 1526.7, slow = 1724.5, runs = 19 },
				},
				[14] = {
					[2124] = { order = 1, name = "Adderis and Aspix", split = 331.9, fast = 316.6, slow = 340.0, runs = 9 },
					[2125] = { order = 2, name = "Merektha", split = 835.4, fast = 803.9, slow = 886.6, runs = 9 },
					[2126] = { order = 3, name = "Galvazzt", split = 1174.2, fast = 1161.2, slow = 1235.8, runs = 9 },
					[2127] = { order = 4, name = "Avatar of Sethraliss", split = 1589.8, fast = 1574.1, slow = 1716.2, runs = 9 },
				},
				[15] = {
					[2124] = { order = 1, name = "Adderis and Aspix", split = 337.9, fast = 325.3, slow = 367.5, runs = 13 },
					[2125] = { order = 2, name = "Merektha", split = 927.2, fast = 870.7, slow = 949.1, runs = 13 },
					[2126] = { order = 3, name = "Galvazzt", split = 1281.6, fast = 1211.4, slow = 1329.4, runs = 13 },
					[2127] = { order = 4, name = "Avatar of Sethraliss", split = 1738.6, fast = 1651.6, slow = 1813.5, runs = 13 },
				},
				[16] = {
					[2124] = { order = 1, name = "Adderis and Aspix", split = 320.0, fast = 315.3, slow = 341.2, runs = 8 },
					[2125] = { order = 2, name = "Merektha", split = 863.7, fast = 839.0, slow = 904.2, runs = 8 },
					[2126] = { order = 3, name = "Galvazzt", split = 1228.9, fast = 1199.8, slow = 1282.8, runs = 8 },
					[2127] = { order = 4, name = "Avatar of Sethraliss", split = 1754.6, fast = 1712.8, slow = 1796.1, runs = 8 },
				},
			},
		},
		[399] = {
			name = "Ruby Life Pools",
			levels = {
				[2] = {
					[2609] = { order = 1, name = "Melidrussa Chillworn", split = 263.8, fast = 247.6, slow = 317.4, runs = 9 },
					[2606] = { order = 2, name = "Kokia Blazehoof", split = 659.6, fast = 622.5, slow = 824.6, runs = 9 },
					[2623] = { order = 3, name = "Kyrakka and Erkhart Stormvein", split = 879.4, fast = 805.1, slow = 1091.6, runs = 9 },
				},
				[4] = {
					[2609] = { order = 1, name = "Melidrussa Chillworn", split = 359.6, fast = 330.0, slow = 378.5, runs = 5 },
					[2606] = { order = 2, name = "Kokia Blazehoof", split = 893.8, fast = 806.7, slow = 937.8, runs = 5 },
					[2623] = { order = 3, name = "Kyrakka and Erkhart Stormvein", split = 1216.4, fast = 1096.7, slow = 1281.5, runs = 5 },
				},
				[7] = {
					[2609] = { order = 1, name = "Melidrussa Chillworn", split = 400.3, fast = 376.8, slow = 437.4, runs = 8 },
					[2606] = { order = 2, name = "Kokia Blazehoof", split = 1020.4, fast = 895.7, slow = 1119.8, runs = 8 },
					[2623] = { order = 3, name = "Kyrakka and Erkhart Stormvein", split = 1336.5, fast = 1211.7, slow = 1459.8, runs = 8 },
				},
				[8] = {
					[2609] = { order = 1, name = "Melidrussa Chillworn", split = 392.8, fast = 366.6, slow = 418.6, runs = 16 },
					[2606] = { order = 2, name = "Kokia Blazehoof", split = 978.6, fast = 932.6, slow = 1121.7, runs = 16 },
					[2623] = { order = 3, name = "Kyrakka and Erkhart Stormvein", split = 1331.5, fast = 1259.7, slow = 1503.5, runs = 16 },
				},
				[9] = {
					[2609] = { order = 1, name = "Melidrussa Chillworn", split = 355.1, fast = 344.1, slow = 429.3, runs = 7 },
					[2606] = { order = 2, name = "Kokia Blazehoof", split = 905.0, fast = 876.2, slow = 1088.8, runs = 7 },
					[2623] = { order = 3, name = "Kyrakka and Erkhart Stormvein", split = 1225.3, fast = 1185.1, slow = 1407.4, runs = 7 },
				},
				[10] = {
					[2609] = { order = 1, name = "Melidrussa Chillworn", split = 403.1, fast = 368.6, slow = 430.0, runs = 61 },
					[2606] = { order = 2, name = "Kokia Blazehoof", split = 1008.3, fast = 902.4, slow = 1090.9, runs = 61 },
					[2623] = { order = 3, name = "Kyrakka and Erkhart Stormvein", split = 1332.9, fast = 1233.5, slow = 1524.5, runs = 61 },
				},
				[11] = {
					[2609] = { order = 1, name = "Melidrussa Chillworn", split = 429.9, fast = 406.1, slow = 458.1, runs = 18 },
					[2606] = { order = 2, name = "Kokia Blazehoof", split = 1097.8, fast = 1002.2, slow = 1190.8, runs = 19 },
					[2623] = { order = 3, name = "Kyrakka and Erkhart Stormvein", split = 1451.7, fast = 1373.3, slow = 1599.4, runs = 19 },
				},
				[12] = {
					[2609] = { order = 1, name = "Melidrussa Chillworn", split = 420.8, fast = 391.4, slow = 456.2, runs = 38 },
					[2606] = { order = 2, name = "Kokia Blazehoof", split = 1016.0, fast = 975.9, slow = 1115.0, runs = 39 },
					[2623] = { order = 3, name = "Kyrakka and Erkhart Stormvein", split = 1405.8, fast = 1309.1, slow = 1535.4, runs = 39 },
				},
				[13] = {
					[2609] = { order = 1, name = "Melidrussa Chillworn", split = 436.0, fast = 421.4, slow = 469.8, runs = 14 },
					[2606] = { order = 2, name = "Kokia Blazehoof", split = 1070.3, fast = 990.2, slow = 1194.4, runs = 14 },
					[2623] = { order = 3, name = "Kyrakka and Erkhart Stormvein", split = 1465.4, fast = 1371.0, slow = 1625.1, runs = 14 },
				},
				[14] = {
					[2609] = { order = 1, name = "Melidrussa Chillworn", split = 451.3, fast = 433.3, slow = 477.4, runs = 19 },
					[2606] = { order = 2, name = "Kokia Blazehoof", split = 1090.0, fast = 1077.2, slow = 1211.4, runs = 19 },
					[2623] = { order = 3, name = "Kyrakka and Erkhart Stormvein", split = 1530.0, fast = 1477.4, slow = 1643.9, runs = 19 },
				},
				[15] = {
					[2609] = { order = 1, name = "Melidrussa Chillworn", split = 442.0, fast = 422.9, slow = 454.0, runs = 15 },
					[2606] = { order = 2, name = "Kokia Blazehoof", split = 1104.3, fast = 1059.9, slow = 1145.3, runs = 15 },
					[2623] = { order = 3, name = "Kyrakka and Erkhart Stormvein", split = 1492.7, fast = 1464.2, slow = 1564.7, runs = 15 },
				},
				[16] = {
					[2609] = { order = 1, name = "Melidrussa Chillworn", split = 466.2, fast = 454.5, slow = 487.5, runs = 8 },
					[2606] = { order = 2, name = "Kokia Blazehoof", split = 1142.8, fast = 1121.1, slow = 1233.9, runs = 8 },
					[2623] = { order = 3, name = "Kyrakka and Erkhart Stormvein", split = 1588.0, fast = 1527.2, slow = 1677.0, runs = 8 },
				},
			},
		},
		[584] = {
			name = "The Blinding Vale",
			levels = {
				[2] = {
					[3199] = { order = 1, name = "Lightblossom Trinity", split = 357.1, fast = 290.0, slow = 392.0, runs = 5 },
					[3200] = { order = 2, name = "Ikuzz the Light Hunter", split = 534.1, fast = 465.3, slow = 583.3, runs = 5 },
					[3201] = { order = 3, name = "Lightwarden Ruia", split = 768.5, fast = 699.3, slow = 787.8, runs = 5 },
					[3202] = { order = 4, name = "Ziekket", split = 1080.0, fast = 977.5, slow = 1084.9, runs = 5 },
				},
				[5] = {
					[3199] = { order = 1, name = "Lightblossom Trinity", split = 353.8, fast = 341.0, slow = 387.8, runs = 7 },
					[3200] = { order = 2, name = "Ikuzz the Light Hunter", split = 551.8, fast = 494.9, slow = 581.5, runs = 7 },
					[3201] = { order = 3, name = "Lightwarden Ruia", split = 797.6, fast = 721.9, slow = 846.4, runs = 7 },
					[3202] = { order = 4, name = "Ziekket", split = 1116.3, fast = 997.3, slow = 1158.8, runs = 7 },
				},
				[6] = {
					[3199] = { order = 1, name = "Lightblossom Trinity", split = 389.1, fast = 387.1, slow = 408.3, runs = 5 },
					[3200] = { order = 2, name = "Ikuzz the Light Hunter", split = 629.2, fast = 588.0, slow = 636.8, runs = 5 },
					[3201] = { order = 3, name = "Lightwarden Ruia", split = 891.3, fast = 861.2, slow = 936.8, runs = 5 },
					[3202] = { order = 4, name = "Ziekket", split = 1242.6, fast = 1187.4, slow = 1349.2, runs = 5 },
				},
				[7] = {
					[3199] = { order = 1, name = "Lightblossom Trinity", split = 414.2, fast = 397.0, slow = 489.5, runs = 8 },
					[3200] = { order = 2, name = "Ikuzz the Light Hunter", split = 624.7, fast = 613.6, slow = 711.8, runs = 8 },
					[3201] = { order = 3, name = "Lightwarden Ruia", split = 914.6, fast = 884.8, slow = 1002.3, runs = 8 },
					[3202] = { order = 4, name = "Ziekket", split = 1266.0, fast = 1252.0, slow = 1417.6, runs = 8 },
				},
				[8] = {
					[3199] = { order = 1, name = "Lightblossom Trinity", split = 459.4, fast = 398.7, slow = 569.8, runs = 7 },
					[3200] = { order = 2, name = "Ikuzz the Light Hunter", split = 572.0, fast = 505.9, slow = 697.5, runs = 7 },
					[3201] = { order = 3, name = "Lightwarden Ruia", split = 1006.6, fast = 908.6, slow = 1041.6, runs = 7 },
					[3202] = { order = 4, name = "Ziekket", split = 1402.3, fast = 1283.0, slow = 1496.1, runs = 7 },
				},
				[9] = {
					[3199] = { order = 1, name = "Lightblossom Trinity", split = 426.9, fast = 381.8, slow = 488.1, runs = 12 },
					[3200] = { order = 2, name = "Ikuzz the Light Hunter", split = 628.9, fast = 607.4, slow = 744.7, runs = 12 },
					[3201] = { order = 3, name = "Lightwarden Ruia", split = 903.7, fast = 885.0, slow = 1117.1, runs = 12 },
					[3202] = { order = 4, name = "Ziekket", split = 1313.4, fast = 1275.6, slow = 1563.4, runs = 12 },
				},
				[10] = {
					[3199] = { order = 1, name = "Lightblossom Trinity", split = 445.0, fast = 407.4, slow = 527.2, runs = 69 },
					[3200] = { order = 2, name = "Ikuzz the Light Hunter", split = 705.6, fast = 625.7, slow = 777.8, runs = 69 },
					[3201] = { order = 3, name = "Lightwarden Ruia", split = 1027.4, fast = 933.4, slow = 1112.6, runs = 70 },
					[3202] = { order = 4, name = "Ziekket", split = 1498.9, fast = 1312.3, slow = 1563.7, runs = 71 },
				},
				[11] = {
					[3199] = { order = 1, name = "Lightblossom Trinity", split = 475.4, fast = 404.7, slow = 596.9, runs = 23 },
					[3200] = { order = 2, name = "Ikuzz the Light Hunter", split = 742.3, fast = 640.9, slow = 824.6, runs = 23 },
					[3201] = { order = 3, name = "Lightwarden Ruia", split = 1063.9, fast = 998.6, slow = 1181.8, runs = 23 },
					[3202] = { order = 4, name = "Ziekket", split = 1458.1, fast = 1406.1, slow = 1691.8, runs = 23 },
				},
				[12] = {
					[3199] = { order = 1, name = "Lightblossom Trinity", split = 468.2, fast = 433.2, slow = 531.9, runs = 48 },
					[3200] = { order = 2, name = "Ikuzz the Light Hunter", split = 733.9, fast = 680.4, slow = 811.8, runs = 48 },
					[3201] = { order = 3, name = "Lightwarden Ruia", split = 1095.3, fast = 1028.4, slow = 1213.6, runs = 48 },
					[3202] = { order = 4, name = "Ziekket", split = 1582.2, fast = 1458.8, slow = 1741.5, runs = 48 },
				},
				[13] = {
					[3199] = { order = 1, name = "Lightblossom Trinity", split = 545.9, fast = 500.4, slow = 590.0, runs = 23 },
					[3200] = { order = 2, name = "Ikuzz the Light Hunter", split = 822.6, fast = 763.6, slow = 871.8, runs = 23 },
					[3201] = { order = 3, name = "Lightwarden Ruia", split = 1200.8, fast = 1143.7, slow = 1255.5, runs = 23 },
					[3202] = { order = 4, name = "Ziekket", split = 1649.4, fast = 1581.8, slow = 1754.7, runs = 23 },
				},
				[14] = {
					[3199] = { order = 1, name = "Lightblossom Trinity", split = 510.1, fast = 460.9, slow = 579.8, runs = 12 },
					[3200] = { order = 2, name = "Ikuzz the Light Hunter", split = 783.2, fast = 725.2, slow = 869.0, runs = 12 },
					[3201] = { order = 3, name = "Lightwarden Ruia", split = 1173.5, fast = 1105.8, slow = 1280.1, runs = 12 },
					[3202] = { order = 4, name = "Ziekket", split = 1641.3, fast = 1567.7, slow = 1809.4, runs = 12 },
				},
				[15] = {
					[3199] = { order = 1, name = "Lightblossom Trinity", split = 473.9, fast = 450.7, slow = 493.3, runs = 13 },
					[3200] = { order = 2, name = "Ikuzz the Light Hunter", split = 764.3, fast = 738.6, slow = 792.0, runs = 13 },
					[3201] = { order = 3, name = "Lightwarden Ruia", split = 1148.1, fast = 1087.7, slow = 1191.8, runs = 13 },
					[3202] = { order = 4, name = "Ziekket", split = 1610.7, fast = 1558.9, slow = 1646.5, runs = 13 },
				},
			},
		},
		[585] = {
			name = "Voidscar Arena",
			levels = {
				[2] = {
					[3285] = { order = 1, name = "Taz'Rah", split = 368.9, fast = 349.5, slow = 400.4, runs = 6 },
					[3286] = { order = 2, name = "Atroxus", split = 654.4, fast = 618.5, slow = 666.4, runs = 6 },
					[3287] = { order = 3, name = "Charonus", split = 1027.2, fast = 964.3, slow = 1038.7, runs = 6 },
				},
				[5] = {
					[3285] = { order = 1, name = "Taz'Rah", split = 401.4, fast = 370.8, slow = 441.1, runs = 7 },
					[3286] = { order = 2, name = "Atroxus", split = 694.1, fast = 640.3, slow = 735.0, runs = 7 },
					[3287] = { order = 3, name = "Charonus", split = 1064.9, fast = 998.9, slow = 1149.0, runs = 7 },
				},
				[6] = {
					[3285] = { order = 1, name = "Taz'Rah", split = 431.6, fast = 416.7, slow = 470.6, runs = 10 },
					[3286] = { order = 2, name = "Atroxus", split = 739.9, fast = 699.5, slow = 795.9, runs = 10 },
					[3287] = { order = 3, name = "Charonus", split = 1181.7, fast = 1103.9, slow = 1253.8, runs = 10 },
				},
				[7] = {
					[3285] = { order = 1, name = "Taz'Rah", split = 555.7, fast = 488.5, slow = 577.5, runs = 9 },
					[3286] = { order = 2, name = "Atroxus", split = 915.7, fast = 795.4, slow = 926.9, runs = 9 },
					[3287] = { order = 3, name = "Charonus", split = 1362.6, fast = 1251.9, slow = 1483.6, runs = 9 },
				},
				[9] = {
					[3285] = { order = 1, name = "Taz'Rah", split = 643.5, fast = 605.9, slow = 654.0, runs = 6 },
					[3286] = { order = 2, name = "Atroxus", split = 1017.3, fast = 990.5, slow = 1118.0, runs = 6 },
					[3287] = { order = 3, name = "Charonus", split = 1570.5, fast = 1497.7, slow = 1663.1, runs = 6 },
				},
				[10] = {
					[3285] = { order = 1, name = "Taz'Rah", split = 511.3, fast = 476.6, slow = 571.8, runs = 77 },
					[3286] = { order = 2, name = "Atroxus", split = 880.8, fast = 803.9, slow = 997.8, runs = 77 },
					[3287] = { order = 3, name = "Charonus", split = 1377.2, fast = 1258.9, slow = 1535.8, runs = 77 },
				},
				[11] = {
					[3285] = { order = 1, name = "Taz'Rah", split = 566.4, fast = 512.5, slow = 636.7, runs = 19 },
					[3286] = { order = 2, name = "Atroxus", split = 946.5, fast = 905.4, slow = 1074.4, runs = 19 },
					[3287] = { order = 3, name = "Charonus", split = 1621.6, fast = 1535.0, slow = 1671.6, runs = 19 },
				},
				[12] = {
					[3285] = { order = 1, name = "Taz'Rah", split = 538.8, fast = 492.9, slow = 599.4, runs = 55 },
					[3286] = { order = 2, name = "Atroxus", split = 924.6, fast = 850.0, slow = 996.3, runs = 56 },
					[3287] = { order = 3, name = "Charonus", split = 1445.6, fast = 1332.9, slow = 1594.2, runs = 56 },
				},
				[13] = {
					[3285] = { order = 1, name = "Taz'Rah", split = 573.1, fast = 518.6, slow = 610.2, runs = 16 },
					[3286] = { order = 2, name = "Atroxus", split = 1009.6, fast = 928.9, slow = 1050.2, runs = 16 },
					[3287] = { order = 3, name = "Charonus", split = 1599.2, fast = 1481.4, slow = 1647.7, runs = 16 },
				},
				[14] = {
					[3285] = { order = 1, name = "Taz'Rah", split = 572.8, fast = 531.5, slow = 585.5, runs = 10 },
					[3286] = { order = 2, name = "Atroxus", split = 974.5, fast = 932.4, slow = 1003.6, runs = 10 },
					[3287] = { order = 3, name = "Charonus", split = 1510.0, fast = 1461.3, slow = 1644.4, runs = 10 },
				},
				[15] = {
					[3285] = { order = 1, name = "Taz'Rah", split = 575.0, fast = 541.7, slow = 625.8, runs = 12 },
					[3286] = { order = 2, name = "Atroxus", split = 987.9, fast = 942.5, slow = 1042.7, runs = 12 },
					[3287] = { order = 3, name = "Charonus", split = 1611.7, fast = 1495.2, slow = 1666.3, runs = 12 },
				},
				[16] = {
					[3285] = { order = 1, name = "Taz'Rah", split = 633.9, fast = 610.7, slow = 664.1, runs = 5 },
					[3286] = { order = 2, name = "Atroxus", split = 1121.4, fast = 1031.5, slow = 1134.8, runs = 5 },
					[3287] = { order = 3, name = "Charonus", split = 1721.9, fast = 1669.5, slow = 1859.8, runs = 5 },
				},
			},
		},
		[586] = {
			name = "Den of Nalorakk",
			levels = {
				[2] = {
					[3207] = { order = 1, name = "The Hoardmonger", split = 431.4, fast = 366.1, slow = 450.9, runs = 8 },
					[3208] = { order = 2, name = "Sentinel of Winter", split = 914.0, fast = 791.4, slow = 948.1, runs = 8 },
					[3209] = { order = 3, name = "Nalorakk", split = 1298.2, fast = 1116.5, slow = 1324.4, runs = 8 },
				},
				[6] = {
					[3207] = { order = 1, name = "The Hoardmonger", split = 418.9, fast = 414.1, slow = 437.7, runs = 5 },
					[3208] = { order = 2, name = "Sentinel of Winter", split = 846.6, fast = 815.1, slow = 862.5, runs = 5 },
					[3209] = { order = 3, name = "Nalorakk", split = 1224.6, fast = 1192.6, slow = 1247.3, runs = 5 },
				},
				[7] = {
					[3207] = { order = 1, name = "The Hoardmonger", split = 545.3, fast = 471.7, slow = 549.1, runs = 5 },
					[3208] = { order = 2, name = "Sentinel of Winter", split = 1049.9, fast = 963.0, slow = 1065.3, runs = 5 },
					[3209] = { order = 3, name = "Nalorakk", split = 1513.0, fast = 1390.7, slow = 1513.8, runs = 5 },
				},
				[8] = {
					[3207] = { order = 1, name = "The Hoardmonger", split = 545.5, fast = 508.3, slow = 616.7, runs = 11 },
					[3208] = { order = 2, name = "Sentinel of Winter", split = 1260.8, fast = 1172.4, slow = 1282.4, runs = 11 },
					[3209] = { order = 3, name = "Nalorakk", split = 1762.0, fast = 1635.2, slow = 1796.3, runs = 11 },
				},
				[9] = {
					[3207] = { order = 1, name = "The Hoardmonger", split = 492.8, fast = 473.0, slow = 525.2, runs = 8 },
					[3208] = { order = 2, name = "Sentinel of Winter", split = 1040.2, fast = 965.4, slow = 1100.2, runs = 9 },
					[3209] = { order = 3, name = "Nalorakk", split = 1526.9, fast = 1408.5, slow = 1590.9, runs = 9 },
				},
				[10] = {
					[3207] = { order = 1, name = "The Hoardmonger", split = 518.2, fast = 466.3, slow = 570.4, runs = 83 },
					[3208] = { order = 2, name = "Sentinel of Winter", split = 1099.4, fast = 998.0, slow = 1224.6, runs = 84 },
					[3209] = { order = 3, name = "Nalorakk", split = 1580.0, fast = 1443.5, slow = 1749.6, runs = 85 },
				},
				[11] = {
					[3207] = { order = 1, name = "The Hoardmonger", split = 529.2, fast = 467.9, slow = 660.9, runs = 22 },
					[3208] = { order = 2, name = "Sentinel of Winter", split = 1139.9, fast = 961.8, slow = 1365.4, runs = 24 },
					[3209] = { order = 3, name = "Nalorakk", split = 1722.1, fast = 1423.1, slow = 1968.1, runs = 24 },
				},
				[12] = {
					[3207] = { order = 1, name = "The Hoardmonger", split = 520.5, fast = 471.3, slow = 576.6, runs = 56 },
					[3208] = { order = 2, name = "Sentinel of Winter", split = 1109.6, fast = 1021.5, slow = 1225.6, runs = 56 },
					[3209] = { order = 3, name = "Nalorakk", split = 1618.3, fast = 1465.9, slow = 1725.0, runs = 56 },
				},
				[13] = {
					[3207] = { order = 1, name = "The Hoardmonger", split = 552.0, fast = 500.3, slow = 586.6, runs = 19 },
					[3208] = { order = 2, name = "Sentinel of Winter", split = 1155.2, fast = 1055.7, slow = 1250.5, runs = 19 },
					[3209] = { order = 3, name = "Nalorakk", split = 1666.7, fast = 1538.3, slow = 1747.3, runs = 19 },
				},
				[14] = {
					[3207] = { order = 1, name = "The Hoardmonger", split = 555.0, fast = 520.0, slow = 623.1, runs = 15 },
					[3208] = { order = 2, name = "Sentinel of Winter", split = 1173.0, fast = 1109.5, slow = 1324.3, runs = 15 },
					[3209] = { order = 3, name = "Nalorakk", split = 1695.1, fast = 1656.9, slow = 1893.8, runs = 15 },
				},
				[15] = {
					[3207] = { order = 1, name = "The Hoardmonger", split = 544.6, fast = 492.7, slow = 571.9, runs = 18 },
					[3208] = { order = 2, name = "Sentinel of Winter", split = 1201.5, fast = 1128.8, slow = 1249.5, runs = 18 },
					[3209] = { order = 3, name = "Nalorakk", split = 1724.9, fast = 1636.9, slow = 1818.9, runs = 18 },
				},
				[16] = {
					[3207] = { order = 1, name = "The Hoardmonger", split = 505.1, fast = 451.7, slow = 522.9, runs = 5 },
					[3208] = { order = 2, name = "Sentinel of Winter", split = 1199.6, fast = 1092.4, slow = 1209.7, runs = 5 },
					[3209] = { order = 3, name = "Nalorakk", split = 1702.7, fast = 1633.0, slow = 1769.4, runs = 5 },
				},
			},
		},
		[587] = {
			name = "Murder Row",
			levels = {
				[2] = {
					[3101] = { order = 0, name = "Kystia Manaheart", split = 368.3, fast = 346.2, slow = 407.7, runs = 6 },
					[3102] = { order = 1, name = "Zaen Bladesorrow", split = 591.8, fast = 534.1, slow = 653.6, runs = 6 },
					[3103] = { order = 3, name = "Xathuux the Annihilator", split = 889.6, fast = 804.8, slow = 941.6, runs = 6 },
					[3105] = { order = 4, name = "Lithiel Cinderfury", split = 1226.6, fast = 1090.1, slow = 1278.8, runs = 6 },
				},
				[6] = {
					[3101] = { order = 0, name = "Kystia Manaheart", split = 327.6, fast = 317.3, slow = 355.9, runs = 7 },
					[3102] = { order = 1, name = "Zaen Bladesorrow", split = 542.3, fast = 531.9, slow = 587.5, runs = 7 },
					[3103] = { order = 3, name = "Xathuux the Annihilator", split = 832.0, fast = 818.1, slow = 906.4, runs = 7 },
					[3105] = { order = 4, name = "Lithiel Cinderfury", split = 1231.9, fast = 1134.0, slow = 1239.6, runs = 7 },
				},
				[7] = {
					[3101] = { order = 0, name = "Kystia Manaheart", split = 499.2, fast = 486.0, slow = 549.9, runs = 7 },
					[3102] = { order = 1, name = "Zaen Bladesorrow", split = 766.9, fast = 759.9, slow = 848.3, runs = 7 },
					[3103] = { order = 3, name = "Xathuux the Annihilator", split = 1181.0, fast = 1145.0, slow = 1261.7, runs = 7 },
					[3105] = { order = 4, name = "Lithiel Cinderfury", split = 1715.2, fast = 1610.3, slow = 1858.0, runs = 7 },
				},
				[8] = {
					[3101] = { order = 0, name = "Kystia Manaheart", split = 414.9, fast = 396.6, slow = 448.0, runs = 8 },
					[3102] = { order = 1, name = "Zaen Bladesorrow", split = 635.4, fast = 602.2, slow = 680.2, runs = 8 },
					[3103] = { order = 3, name = "Xathuux the Annihilator", split = 965.9, fast = 899.9, slow = 1054.8, runs = 8 },
					[3105] = { order = 4, name = "Lithiel Cinderfury", split = 1371.6, fast = 1242.0, slow = 1470.5, runs = 8 },
				},
				[9] = {
					[3101] = { order = 0, name = "Kystia Manaheart", split = 465.7, fast = 397.5, slow = 527.3, runs = 18 },
					[3102] = { order = 1, name = "Zaen Bladesorrow", split = 714.8, fast = 619.4, slow = 816.8, runs = 18 },
					[3103] = { order = 3, name = "Xathuux the Annihilator", split = 1104.0, fast = 976.4, slow = 1232.6, runs = 18 },
					[3105] = { order = 4, name = "Lithiel Cinderfury", split = 1497.4, fast = 1378.9, slow = 1745.2, runs = 18 },
				},
				[10] = {
					[3101] = { order = 0, name = "Kystia Manaheart", split = 441.5, fast = 391.8, slow = 510.3, runs = 117 },
					[3102] = { order = 1, name = "Zaen Bladesorrow", split = 701.1, fast = 632.4, slow = 802.1, runs = 117 },
					[3103] = { order = 3, name = "Xathuux the Annihilator", split = 1088.6, fast = 981.8, slow = 1238.0, runs = 117 },
					[3105] = { order = 4, name = "Lithiel Cinderfury", split = 1538.3, fast = 1370.7, slow = 1727.0, runs = 117 },
				},
				[11] = {
					[3101] = { order = 0, name = "Kystia Manaheart", split = 452.8, fast = 421.4, slow = 528.4, runs = 44 },
					[3102] = { order = 1, name = "Zaen Bladesorrow", split = 720.9, fast = 674.5, slow = 826.0, runs = 44 },
					[3103] = { order = 3, name = "Xathuux the Annihilator", split = 1136.1, fast = 1015.2, slow = 1305.5, runs = 44 },
					[3105] = { order = 4, name = "Lithiel Cinderfury", split = 1548.0, fast = 1416.0, slow = 1838.5, runs = 45 },
				},
				[12] = {
					[3101] = { order = 0, name = "Kystia Manaheart", split = 452.9, fast = 412.0, slow = 499.0, runs = 67 },
					[3102] = { order = 1, name = "Zaen Bladesorrow", split = 726.5, fast = 671.3, slow = 791.3, runs = 68 },
					[3103] = { order = 3, name = "Xathuux the Annihilator", split = 1145.9, fast = 1047.9, slow = 1242.4, runs = 68 },
					[3105] = { order = 4, name = "Lithiel Cinderfury", split = 1626.3, fast = 1487.0, slow = 1759.7, runs = 68 },
				},
				[13] = {
					[3101] = { order = 0, name = "Kystia Manaheart", split = 448.2, fast = 429.9, slow = 498.7, runs = 21 },
					[3102] = { order = 1, name = "Zaen Bladesorrow", split = 725.7, fast = 706.8, slow = 807.6, runs = 21 },
					[3103] = { order = 3, name = "Xathuux the Annihilator", split = 1149.7, fast = 1132.1, slow = 1287.8, runs = 21 },
					[3105] = { order = 4, name = "Lithiel Cinderfury", split = 1663.2, fast = 1576.4, slow = 1952.0, runs = 21 },
				},
				[14] = {
					[3101] = { order = 0, name = "Kystia Manaheart", split = 505.7, fast = 477.3, slow = 566.6, runs = 20 },
					[3102] = { order = 1, name = "Zaen Bladesorrow", split = 788.0, fast = 749.6, slow = 898.3, runs = 20 },
					[3103] = { order = 3, name = "Xathuux the Annihilator", split = 1306.1, fast = 1223.9, slow = 1410.8, runs = 20 },
					[3105] = { order = 4, name = "Lithiel Cinderfury", split = 1848.2, fast = 1692.6, slow = 1970.5, runs = 20 },
				},
				[15] = {
					[3101] = { order = 0, name = "Kystia Manaheart", split = 487.8, fast = 477.8, slow = 505.9, runs = 10 },
					[3102] = { order = 1, name = "Zaen Bladesorrow", split = 775.3, fast = 756.8, slow = 822.8, runs = 10 },
					[3103] = { order = 3, name = "Xathuux the Annihilator", split = 1262.2, fast = 1204.4, slow = 1334.0, runs = 10 },
					[3105] = { order = 4, name = "Lithiel Cinderfury", split = 1821.8, fast = 1699.0, slow = 1886.2, runs = 10 },
				},
				[16] = {
					[3101] = { order = 0, name = "Kystia Manaheart", split = 522.5, fast = 477.2, slow = 531.1, runs = 11 },
					[3102] = { order = 1, name = "Zaen Bladesorrow", split = 798.6, fast = 758.8, slow = 826.4, runs = 11 },
					[3103] = { order = 3, name = "Xathuux the Annihilator", split = 1261.4, fast = 1244.6, slow = 1328.9, runs = 11 },
					[3105] = { order = 4, name = "Lithiel Cinderfury", split = 1856.8, fast = 1795.9, slow = 1891.2, runs = 11 },
				},
			},
		},
		[588] = {
			name = "Altar of Fangs",
			levels = {
				[5] = {
					[3456] = { order = 1, name = "Rav'i", split = 441.6, fast = 398.3, slow = 465.9, runs = 6 },
					[3457] = { order = 2, name = "The Writhing Coil", split = 719.5, fast = 653.3, slow = 778.5, runs = 6 },
					[3458] = { order = 3, name = "Zul'jan", split = 1149.2, fast = 1055.9, slow = 1254.3, runs = 6 },
				},
				[6] = {
					[3456] = { order = 1, name = "Rav'i", split = 511.1, fast = 434.7, slow = 524.4, runs = 9 },
					[3457] = { order = 2, name = "The Writhing Coil", split = 818.0, fast = 740.8, slow = 863.0, runs = 9 },
					[3458] = { order = 3, name = "Zul'jan", split = 1314.7, fast = 1160.4, slow = 1391.4, runs = 9 },
				},
				[7] = {
					[3456] = { order = 1, name = "Rav'i", split = 466.4, fast = 410.2, slow = 494.4, runs = 5 },
					[3457] = { order = 2, name = "The Writhing Coil", split = 752.2, fast = 688.4, slow = 842.5, runs = 5 },
					[3458] = { order = 3, name = "Zul'jan", split = 1201.5, fast = 1130.0, slow = 1354.4, runs = 5 },
				},
				[8] = {
					[3456] = { order = 1, name = "Rav'i", split = 510.6, fast = 468.7, slow = 551.7, runs = 10 },
					[3457] = { order = 2, name = "The Writhing Coil", split = 842.9, fast = 795.0, slow = 909.5, runs = 10 },
					[3458] = { order = 3, name = "Zul'jan", split = 1364.6, fast = 1321.0, slow = 1480.2, runs = 10 },
				},
				[9] = {
					[3456] = { order = 1, name = "Rav'i", split = 539.8, fast = 477.2, slow = 559.2, runs = 10 },
					[3457] = { order = 2, name = "The Writhing Coil", split = 863.4, fast = 834.9, slow = 904.7, runs = 10 },
					[3458] = { order = 3, name = "Zul'jan", split = 1372.6, fast = 1339.3, slow = 1415.3, runs = 10 },
				},
				[10] = {
					[3456] = { order = 1, name = "Rav'i", split = 555.4, fast = 512.0, slow = 634.4, runs = 77 },
					[3457] = { order = 2, name = "The Writhing Coil", split = 939.9, fast = 848.3, slow = 1072.9, runs = 77 },
					[3458] = { order = 3, name = "Zul'jan", split = 1477.5, fast = 1357.9, slow = 1683.4, runs = 77 },
				},
				[11] = {
					[3456] = { order = 1, name = "Rav'i", split = 566.5, fast = 548.1, slow = 616.7, runs = 28 },
					[3457] = { order = 2, name = "The Writhing Coil", split = 952.8, fast = 900.5, slow = 1028.9, runs = 28 },
					[3458] = { order = 3, name = "Zul'jan", split = 1491.6, fast = 1396.6, slow = 1653.8, runs = 29 },
				},
				[12] = {
					[3456] = { order = 1, name = "Rav'i", split = 588.8, fast = 555.2, slow = 655.3, runs = 59 },
					[3457] = { order = 2, name = "The Writhing Coil", split = 999.5, fast = 930.6, slow = 1086.5, runs = 59 },
					[3458] = { order = 3, name = "Zul'jan", split = 1574.0, fast = 1469.8, slow = 1668.4, runs = 59 },
				},
				[13] = {
					[3456] = { order = 1, name = "Rav'i", split = 621.7, fast = 584.2, slow = 645.3, runs = 26 },
					[3457] = { order = 2, name = "The Writhing Coil", split = 1014.0, fast = 987.3, slow = 1078.9, runs = 26 },
					[3458] = { order = 3, name = "Zul'jan", split = 1613.8, fast = 1552.9, slow = 1699.5, runs = 26 },
				},
				[14] = {
					[3456] = { order = 1, name = "Rav'i", split = 651.6, fast = 616.1, slow = 683.0, runs = 21 },
					[3457] = { order = 2, name = "The Writhing Coil", split = 1066.3, fast = 1002.3, slow = 1124.6, runs = 21 },
					[3458] = { order = 3, name = "Zul'jan", split = 1697.1, fast = 1578.8, slow = 1785.6, runs = 21 },
				},
				[15] = {
					[3456] = { order = 1, name = "Rav'i", split = 663.9, fast = 608.3, slow = 701.2, runs = 22 },
					[3457] = { order = 2, name = "The Writhing Coil", split = 1088.0, fast = 1018.5, slow = 1144.8, runs = 22 },
					[3458] = { order = 3, name = "Zul'jan", split = 1713.3, fast = 1631.0, slow = 1800.1, runs = 22 },
				},
				[16] = {
					[3456] = { order = 1, name = "Rav'i", split = 652.2, fast = 650.0, slow = 674.9, runs = 7 },
					[3457] = { order = 2, name = "The Writhing Coil", split = 1089.2, fast = 1065.2, slow = 1114.7, runs = 7 },
					[3458] = { order = 3, name = "Zul'jan", split = 1689.4, fast = 1687.0, slow = 1763.0, runs = 7 },
				},
			},
		},
	},
}
