local _, addonTable = ...

-- Benchmark boss splits for PeaversSplits.
--
-- A SPLIT is the time from the start of a keystone run to a boss dying. For
-- each dungeon and each exact keystone level this holds what the middle of
-- the pool does at every boss, so a running key can be told how far ahead or
-- behind it is while there is still something to do about it.
--
-- Schema:
--   updated   = "YYYY-MM-DD HH:MM:SS" (UTC)
--   partition = the game patch these pools were built on, "major.minor"
--   dungeons  = [mapChallengeModeID].levels[keystoneLevel][DungeonEncounterID]
--             = { order, name, split, fast, slow, runs }
--
-- `split` is the pool's median, `fast`/`slow` its p25/p75, all in SECONDS
-- from the start of the run. `runs` is the sample the figures rest on and is
-- per boss, not per level: a depleted run that ended at the third boss counts
-- toward the first two and not the last.
--
-- EXACT keystone level, never a band. Enemy health scales per level, so a
-- +19 is genuinely slower than a +10 for reasons that are not the group's
-- doing, and a level with no entry means no pool cleared the sample floor -
-- not that the run cannot be measured. Consumers must say so rather than
-- reaching for a neighbouring level.
--
-- ONE PARTITION ONLY. Every dungeon here was keyed on the same patch, so
-- nothing in this file can be compared against a pool from another one. A
-- dungeon rotated out of the current season simply has no entry.
--
-- Auto-generated by splits-module (PeaversAddonDataSupplier) from
-- parses.gg /api/keys/{id}/splits. Do not edit by hand.
addonTable.SplitsData = {
	updated = "2026-09-21 05:00:46",
	partition = "12.1",

	dungeons = {
		[249] = {
			name = "Kings' Rest",
			levels = {
				[5] = {
					[2139] = { order = 1, name = "The Golden Serpent", split = 302.7, fast = 264.3, slow = 321.3, runs = 6 },
					[2142] = { order = 2, name = "Mchimba the Embalmer", split = 777.2, fast = 710.8, slow = 804.3, runs = 6 },
					[2140] = { order = 3, name = "The Council of Tribes", split = 1135.2, fast = 990.4, slow = 1199.9, runs = 6 },
					[2143] = { order = 4, name = "Dazar, The First King", split = 1370.8, fast = 1244.2, slow = 1423.2, runs = 6 },
				},
				[7] = {
					[2139] = { order = 1, name = "The Golden Serpent", split = 315.0, fast = 302.9, slow = 351.9, runs = 14 },
					[2142] = { order = 2, name = "Mchimba the Embalmer", split = 910.8, fast = 793.9, slow = 959.4, runs = 14 },
					[2140] = { order = 3, name = "The Council of Tribes", split = 1265.2, fast = 1139.5, slow = 1321.0, runs = 14 },
					[2143] = { order = 4, name = "Dazar, The First King", split = 1531.3, fast = 1355.7, slow = 1602.1, runs = 14 },
				},
				[8] = {
					[2139] = { order = 1, name = "The Golden Serpent", split = 311.7, fast = 280.5, slow = 348.4, runs = 10 },
					[2142] = { order = 2, name = "Mchimba the Embalmer", split = 800.8, fast = 783.7, slow = 930.2, runs = 10 },
					[2140] = { order = 3, name = "The Council of Tribes", split = 1128.9, fast = 1100.3, slow = 1306.2, runs = 10 },
					[2143] = { order = 4, name = "Dazar, The First King", split = 1334.8, fast = 1326.5, slow = 1532.7, runs = 10 },
				},
				[9] = {
					[2139] = { order = 1, name = "The Golden Serpent", split = 393.8, fast = 356.6, slow = 439.4, runs = 10 },
					[2142] = { order = 2, name = "Mchimba the Embalmer", split = 967.4, fast = 946.6, slow = 1023.7, runs = 10 },
					[2140] = { order = 3, name = "The Council of Tribes", split = 1359.2, fast = 1329.2, slow = 1428.4, runs = 10 },
					[2143] = { order = 4, name = "Dazar, The First King", split = 1602.6, fast = 1588.1, slow = 1684.3, runs = 10 },
				},
				[10] = {
					[2139] = { order = 1, name = "The Golden Serpent", split = 364.6, fast = 313.3, slow = 393.7, runs = 61 },
					[2142] = { order = 2, name = "Mchimba the Embalmer", split = 905.5, fast = 821.8, slow = 1013.8, runs = 62 },
					[2140] = { order = 3, name = "The Council of Tribes", split = 1286.3, fast = 1168.7, slow = 1429.4, runs = 62 },
					[2143] = { order = 4, name = "Dazar, The First King", split = 1551.3, fast = 1412.8, slow = 1737.5, runs = 62 },
				},
				[11] = {
					[2139] = { order = 1, name = "The Golden Serpent", split = 387.4, fast = 342.5, slow = 422.0, runs = 17 },
					[2142] = { order = 2, name = "Mchimba the Embalmer", split = 949.6, fast = 860.8, slow = 1062.8, runs = 17 },
					[2140] = { order = 3, name = "The Council of Tribes", split = 1364.7, fast = 1269.2, slow = 1542.0, runs = 17 },
					[2143] = { order = 4, name = "Dazar, The First King", split = 1651.1, fast = 1526.4, slow = 1852.5, runs = 17 },
				},
				[12] = {
					[2139] = { order = 1, name = "The Golden Serpent", split = 387.1, fast = 358.4, slow = 428.1, runs = 30 },
					[2142] = { order = 2, name = "Mchimba the Embalmer", split = 986.9, fast = 947.4, slow = 1043.6, runs = 31 },
					[2140] = { order = 3, name = "The Council of Tribes", split = 1390.0, fast = 1339.8, slow = 1504.9, runs = 31 },
					[2143] = { order = 4, name = "Dazar, The First King", split = 1672.7, fast = 1612.2, slow = 1800.6, runs = 31 },
				},
				[13] = {
					[2139] = { order = 1, name = "The Golden Serpent", split = 376.9, fast = 361.9, slow = 401.5, runs = 11 },
					[2142] = { order = 2, name = "Mchimba the Embalmer", split = 1010.5, fast = 950.5, slow = 1047.8, runs = 11 },
					[2140] = { order = 3, name = "The Council of Tribes", split = 1428.6, fast = 1375.7, slow = 1502.5, runs = 11 },
					[2143] = { order = 4, name = "Dazar, The First King", split = 1775.7, fast = 1659.8, slow = 1848.0, runs = 11 },
				},
				[14] = {
					[2139] = { order = 1, name = "The Golden Serpent", split = 376.9, fast = 361.0, slow = 398.3, runs = 7 },
					[2142] = { order = 2, name = "Mchimba the Embalmer", split = 1019.9, fast = 965.4, slow = 1070.9, runs = 7 },
					[2140] = { order = 3, name = "The Council of Tribes", split = 1484.6, fast = 1413.6, slow = 1549.5, runs = 8 },
					[2143] = { order = 4, name = "Dazar, The First King", split = 1763.8, fast = 1705.9, slow = 1849.1, runs = 8 },
				},
				[15] = {
					[2139] = { order = 1, name = "The Golden Serpent", split = 384.3, fast = 377.7, slow = 425.3, runs = 7 },
					[2142] = { order = 2, name = "Mchimba the Embalmer", split = 1063.5, fast = 1025.0, slow = 1083.3, runs = 7 },
					[2140] = { order = 3, name = "The Council of Tribes", split = 1506.2, fast = 1471.7, slow = 1548.6, runs = 7 },
					[2143] = { order = 4, name = "Dazar, The First King", split = 1842.3, fast = 1790.9, slow = 1880.2, runs = 7 },
				},
			},
		},
		[250] = {
			name = "Temple of Sethraliss",
			levels = {
				[2] = {
					[2124] = { order = 1, name = "Adderis and Aspix", split = 238.3, fast = 198.2, slow = 247.2, runs = 7 },
					[2125] = { order = 2, name = "Merektha", split = 596.9, fast = 470.7, slow = 627.9, runs = 7 },
					[2126] = { order = 3, name = "Galvazzt", split = 817.0, fast = 685.1, slow = 865.3, runs = 7 },
					[2127] = { order = 4, name = "Avatar of Sethraliss", split = 1209.3, fast = 1067.0, slow = 1267.3, runs = 7 },
				},
				[6] = {
					[2124] = { order = 1, name = "Adderis and Aspix", split = 247.8, fast = 216.4, slow = 265.7, runs = 6 },
					[2125] = { order = 2, name = "Merektha", split = 645.5, fast = 514.3, slow = 731.4, runs = 6 },
					[2126] = { order = 3, name = "Galvazzt", split = 862.1, fast = 706.9, slow = 977.0, runs = 6 },
					[2127] = { order = 4, name = "Avatar of Sethraliss", split = 1373.3, fast = 1249.0, slow = 1669.2, runs = 6 },
				},
				[7] = {
					[2124] = { order = 1, name = "Adderis and Aspix", split = 300.4, fast = 252.1, slow = 336.3, runs = 6 },
					[2125] = { order = 2, name = "Merektha", split = 737.1, fast = 661.7, slow = 846.8, runs = 6 },
					[2126] = { order = 3, name = "Galvazzt", split = 1046.2, fast = 939.3, slow = 1181.9, runs = 6 },
					[2127] = { order = 4, name = "Avatar of Sethraliss", split = 1692.5, fast = 1464.0, slow = 1751.0, runs = 6 },
				},
				[8] = {
					[2124] = { order = 1, name = "Adderis and Aspix", split = 257.8, fast = 253.2, slow = 262.5, runs = 6 },
					[2125] = { order = 2, name = "Merektha", split = 647.1, fast = 607.0, slow = 676.0, runs = 6 },
					[2126] = { order = 3, name = "Galvazzt", split = 891.3, fast = 844.6, slow = 944.2, runs = 6 },
					[2127] = { order = 4, name = "Avatar of Sethraliss", split = 1348.3, fast = 1280.5, slow = 1391.6, runs = 6 },
				},
				[9] = {
					[2124] = { order = 1, name = "Adderis and Aspix", split = 298.7, fast = 275.1, slow = 316.5, runs = 14 },
					[2125] = { order = 2, name = "Merektha", split = 756.4, fast = 707.6, slow = 799.4, runs = 14 },
					[2126] = { order = 3, name = "Galvazzt", split = 1053.7, fast = 984.5, slow = 1119.5, runs = 14 },
					[2127] = { order = 4, name = "Avatar of Sethraliss", split = 1555.2, fast = 1471.9, slow = 1601.1, runs = 14 },
				},
				[10] = {
					[2124] = { order = 1, name = "Adderis and Aspix", split = 306.2, fast = 265.9, slow = 336.2, runs = 66 },
					[2125] = { order = 2, name = "Merektha", split = 778.7, fast = 668.7, slow = 871.7, runs = 66 },
					[2126] = { order = 3, name = "Galvazzt", split = 1092.1, fast = 943.3, slow = 1207.5, runs = 66 },
					[2127] = { order = 4, name = "Avatar of Sethraliss", split = 1565.8, fast = 1384.5, slow = 1760.3, runs = 66 },
				},
				[11] = {
					[2124] = { order = 1, name = "Adderis and Aspix", split = 299.6, fast = 292.7, slow = 319.1, runs = 17 },
					[2125] = { order = 2, name = "Merektha", split = 809.3, fast = 773.8, slow = 878.7, runs = 17 },
					[2126] = { order = 3, name = "Galvazzt", split = 1142.1, fast = 1069.6, slow = 1264.3, runs = 17 },
					[2127] = { order = 4, name = "Avatar of Sethraliss", split = 1599.7, fast = 1477.5, slow = 1806.6, runs = 17 },
				},
				[12] = {
					[2124] = { order = 1, name = "Adderis and Aspix", split = 300.1, fast = 277.6, slow = 327.0, runs = 36 },
					[2125] = { order = 2, name = "Merektha", split = 772.8, fast = 748.2, slow = 841.2, runs = 36 },
					[2126] = { order = 3, name = "Galvazzt", split = 1077.4, fast = 1044.1, slow = 1181.3, runs = 36 },
					[2127] = { order = 4, name = "Avatar of Sethraliss", split = 1570.1, fast = 1476.7, slow = 1705.1, runs = 36 },
				},
				[13] = {
					[2124] = { order = 1, name = "Adderis and Aspix", split = 313.3, fast = 289.5, slow = 334.8, runs = 14 },
					[2125] = { order = 2, name = "Merektha", split = 813.3, fast = 766.1, slow = 858.4, runs = 15 },
					[2126] = { order = 3, name = "Galvazzt", split = 1163.6, fast = 1086.7, slow = 1224.3, runs = 15 },
					[2127] = { order = 4, name = "Avatar of Sethraliss", split = 1612.9, fast = 1551.2, slow = 1753.0, runs = 15 },
				},
				[14] = {
					[2124] = { order = 1, name = "Adderis and Aspix", split = 332.7, fast = 326.6, slow = 338.4, runs = 6 },
					[2125] = { order = 2, name = "Merektha", split = 863.9, fast = 836.8, slow = 942.6, runs = 6 },
					[2126] = { order = 3, name = "Galvazzt", split = 1214.7, fast = 1179.1, slow = 1325.1, runs = 6 },
					[2127] = { order = 4, name = "Avatar of Sethraliss", split = 1715.6, fast = 1609.5, slow = 1827.4, runs = 6 },
				},
				[15] = {
					[2124] = { order = 1, name = "Adderis and Aspix", split = 337.9, fast = 330.2, slow = 375.9, runs = 7 },
					[2125] = { order = 2, name = "Merektha", split = 949.1, fast = 914.6, slow = 969.2, runs = 7 },
					[2126] = { order = 3, name = "Galvazzt", split = 1327.0, fast = 1273.3, slow = 1332.2, runs = 7 },
					[2127] = { order = 4, name = "Avatar of Sethraliss", split = 1751.4, fast = 1731.4, slow = 1819.0, runs = 7 },
				},
			},
		},
		[399] = {
			name = "Ruby Life Pools",
			levels = {
				[2] = {
					[2609] = { order = 1, name = "Melidrussa Chillworn", split = 263.8, fast = 247.6, slow = 317.4, runs = 9 },
					[2606] = { order = 2, name = "Kokia Blazehoof", split = 659.6, fast = 622.5, slow = 824.6, runs = 9 },
					[2623] = { order = 3, name = "Kyrakka and Erkhart Stormvein", split = 879.4, fast = 805.1, slow = 1091.6, runs = 9 },
				},
				[4] = {
					[2609] = { order = 1, name = "Melidrussa Chillworn", split = 359.6, fast = 330.0, slow = 378.5, runs = 5 },
					[2606] = { order = 2, name = "Kokia Blazehoof", split = 893.8, fast = 806.7, slow = 937.8, runs = 5 },
					[2623] = { order = 3, name = "Kyrakka and Erkhart Stormvein", split = 1216.4, fast = 1096.7, slow = 1281.5, runs = 5 },
				},
				[7] = {
					[2609] = { order = 1, name = "Melidrussa Chillworn", split = 400.3, fast = 376.8, slow = 437.4, runs = 8 },
					[2606] = { order = 2, name = "Kokia Blazehoof", split = 1020.4, fast = 895.7, slow = 1119.8, runs = 8 },
					[2623] = { order = 3, name = "Kyrakka and Erkhart Stormvein", split = 1336.5, fast = 1211.7, slow = 1459.8, runs = 8 },
				},
				[8] = {
					[2609] = { order = 1, name = "Melidrussa Chillworn", split = 392.8, fast = 366.6, slow = 418.6, runs = 16 },
					[2606] = { order = 2, name = "Kokia Blazehoof", split = 978.6, fast = 932.6, slow = 1121.7, runs = 16 },
					[2623] = { order = 3, name = "Kyrakka and Erkhart Stormvein", split = 1331.5, fast = 1259.7, slow = 1503.5, runs = 16 },
				},
				[9] = {
					[2609] = { order = 1, name = "Melidrussa Chillworn", split = 354.0, fast = 339.7, slow = 393.8, runs = 6 },
					[2606] = { order = 2, name = "Kokia Blazehoof", split = 904.7, fast = 862.0, slow = 1003.1, runs = 6 },
					[2623] = { order = 3, name = "Kyrakka and Erkhart Stormvein", split = 1218.9, fast = 1171.4, slow = 1306.2, runs = 6 },
				},
				[10] = {
					[2609] = { order = 1, name = "Melidrussa Chillworn", split = 404.3, fast = 370.7, slow = 435.1, runs = 52 },
					[2606] = { order = 2, name = "Kokia Blazehoof", split = 1008.5, fast = 923.4, slow = 1091.0, runs = 52 },
					[2623] = { order = 3, name = "Kyrakka and Erkhart Stormvein", split = 1343.9, fast = 1262.1, slow = 1525.3, runs = 52 },
				},
				[11] = {
					[2609] = { order = 1, name = "Melidrussa Chillworn", split = 429.9, fast = 406.1, slow = 458.1, runs = 18 },
					[2606] = { order = 2, name = "Kokia Blazehoof", split = 1097.8, fast = 1002.2, slow = 1190.8, runs = 19 },
					[2623] = { order = 3, name = "Kyrakka and Erkhart Stormvein", split = 1451.7, fast = 1373.3, slow = 1599.4, runs = 19 },
				},
				[12] = {
					[2609] = { order = 1, name = "Melidrussa Chillworn", split = 433.1, fast = 400.7, slow = 456.2, runs = 30 },
					[2606] = { order = 2, name = "Kokia Blazehoof", split = 1048.5, fast = 984.6, slow = 1130.6, runs = 31 },
					[2623] = { order = 3, name = "Kyrakka and Erkhart Stormvein", split = 1410.8, fast = 1350.3, slow = 1548.6, runs = 31 },
				},
				[13] = {
					[2609] = { order = 1, name = "Melidrussa Chillworn", split = 438.3, fast = 427.5, slow = 465.2, runs = 9 },
					[2606] = { order = 2, name = "Kokia Blazehoof", split = 1110.7, fast = 993.1, slow = 1167.4, runs = 9 },
					[2623] = { order = 3, name = "Kyrakka and Erkhart Stormvein", split = 1495.7, fast = 1387.2, slow = 1589.3, runs = 9 },
				},
				[14] = {
					[2609] = { order = 1, name = "Melidrussa Chillworn", split = 464.8, fast = 441.6, slow = 479.0, runs = 13 },
					[2606] = { order = 2, name = "Kokia Blazehoof", split = 1126.0, fast = 1085.3, slow = 1239.4, runs = 13 },
					[2623] = { order = 3, name = "Kyrakka and Erkhart Stormvein", split = 1568.2, fast = 1506.8, slow = 1655.0, runs = 13 },
				},
				[15] = {
					[2609] = { order = 1, name = "Melidrussa Chillworn", split = 422.9, fast = 410.4, slow = 447.6, runs = 6 },
					[2606] = { order = 2, name = "Kokia Blazehoof", split = 1090.5, fast = 1069.5, slow = 1139.0, runs = 6 },
					[2623] = { order = 3, name = "Kyrakka and Erkhart Stormvein", split = 1483.1, fast = 1469.2, slow = 1550.3, runs = 6 },
				},
			},
		},
		[584] = {
			name = "The Blinding Vale",
			levels = {
				[5] = {
					[3199] = { order = 1, name = "Lightblossom Trinity", split = 362.3, fast = 339.0, slow = 391.9, runs = 6 },
					[3200] = { order = 2, name = "Ikuzz the Light Hunter", split = 530.4, fast = 487.9, slow = 575.6, runs = 6 },
					[3201] = { order = 3, name = "Lightwarden Ruia", split = 762.4, fast = 719.2, slow = 835.4, runs = 6 },
					[3202] = { order = 4, name = "Ziekket", split = 1060.0, fast = 994.0, slow = 1119.4, runs = 6 },
				},
				[6] = {
					[3199] = { order = 1, name = "Lightblossom Trinity", split = 389.1, fast = 387.1, slow = 408.3, runs = 5 },
					[3200] = { order = 2, name = "Ikuzz the Light Hunter", split = 629.2, fast = 588.0, slow = 636.8, runs = 5 },
					[3201] = { order = 3, name = "Lightwarden Ruia", split = 891.3, fast = 861.2, slow = 936.8, runs = 5 },
					[3202] = { order = 4, name = "Ziekket", split = 1242.6, fast = 1187.4, slow = 1349.2, runs = 5 },
				},
				[7] = {
					[3199] = { order = 1, name = "Lightblossom Trinity", split = 414.2, fast = 397.0, slow = 489.5, runs = 8 },
					[3200] = { order = 2, name = "Ikuzz the Light Hunter", split = 624.7, fast = 613.6, slow = 711.8, runs = 8 },
					[3201] = { order = 3, name = "Lightwarden Ruia", split = 914.6, fast = 884.8, slow = 1002.3, runs = 8 },
					[3202] = { order = 4, name = "Ziekket", split = 1266.0, fast = 1252.0, slow = 1417.6, runs = 8 },
				},
				[8] = {
					[3199] = { order = 1, name = "Lightblossom Trinity", split = 459.4, fast = 398.7, slow = 569.8, runs = 7 },
					[3200] = { order = 2, name = "Ikuzz the Light Hunter", split = 572.0, fast = 505.9, slow = 697.5, runs = 7 },
					[3201] = { order = 3, name = "Lightwarden Ruia", split = 1006.6, fast = 908.6, slow = 1041.6, runs = 7 },
					[3202] = { order = 4, name = "Ziekket", split = 1402.3, fast = 1283.0, slow = 1496.1, runs = 7 },
				},
				[9] = {
					[3199] = { order = 1, name = "Lightblossom Trinity", split = 426.9, fast = 381.8, slow = 488.1, runs = 12 },
					[3200] = { order = 2, name = "Ikuzz the Light Hunter", split = 628.9, fast = 607.4, slow = 744.7, runs = 12 },
					[3201] = { order = 3, name = "Lightwarden Ruia", split = 903.7, fast = 885.0, slow = 1117.1, runs = 12 },
					[3202] = { order = 4, name = "Ziekket", split = 1313.4, fast = 1275.6, slow = 1563.4, runs = 12 },
				},
				[10] = {
					[3199] = { order = 1, name = "Lightblossom Trinity", split = 446.4, fast = 412.8, slow = 527.2, runs = 61 },
					[3200] = { order = 2, name = "Ikuzz the Light Hunter", split = 716.8, fast = 645.1, slow = 779.4, runs = 61 },
					[3201] = { order = 3, name = "Lightwarden Ruia", split = 1035.5, fast = 947.5, slow = 1132.5, runs = 62 },
					[3202] = { order = 4, name = "Ziekket", split = 1501.8, fast = 1312.3, slow = 1575.9, runs = 63 },
				},
				[11] = {
					[3199] = { order = 1, name = "Lightblossom Trinity", split = 481.9, fast = 429.2, slow = 616.3, runs = 20 },
					[3200] = { order = 2, name = "Ikuzz the Light Hunter", split = 755.7, fast = 671.9, slow = 871.2, runs = 20 },
					[3201] = { order = 3, name = "Lightwarden Ruia", split = 1079.5, fast = 1019.8, slow = 1231.8, runs = 20 },
					[3202] = { order = 4, name = "Ziekket", split = 1525.8, fast = 1423.4, slow = 1747.3, runs = 20 },
				},
				[12] = {
					[3199] = { order = 1, name = "Lightblossom Trinity", split = 472.4, fast = 446.4, slow = 528.3, runs = 32 },
					[3200] = { order = 2, name = "Ikuzz the Light Hunter", split = 736.4, fast = 701.6, slow = 788.0, runs = 32 },
					[3201] = { order = 3, name = "Lightwarden Ruia", split = 1111.4, fast = 1058.4, slow = 1200.4, runs = 32 },
					[3202] = { order = 4, name = "Ziekket", split = 1622.9, fast = 1508.4, slow = 1703.1, runs = 32 },
				},
				[13] = {
					[3199] = { order = 1, name = "Lightblossom Trinity", split = 552.2, fast = 513.6, slow = 588.7, runs = 20 },
					[3200] = { order = 2, name = "Ikuzz the Light Hunter", split = 827.5, fast = 779.5, slow = 867.0, runs = 20 },
					[3201] = { order = 3, name = "Lightwarden Ruia", split = 1198.9, fast = 1147.8, slow = 1235.0, runs = 20 },
					[3202] = { order = 4, name = "Ziekket", split = 1646.8, fast = 1585.1, slow = 1712.2, runs = 20 },
				},
				[14] = {
					[3199] = { order = 1, name = "Lightblossom Trinity", split = 467.9, fast = 448.1, slow = 574.4, runs = 9 },
					[3200] = { order = 2, name = "Ikuzz the Light Hunter", split = 770.9, fast = 732.1, slow = 878.9, runs = 9 },
					[3201] = { order = 3, name = "Lightwarden Ruia", split = 1130.1, fast = 1087.2, slow = 1272.9, runs = 9 },
					[3202] = { order = 4, name = "Ziekket", split = 1613.0, fast = 1557.6, slow = 1771.8, runs = 9 },
				},
				[15] = {
					[3199] = { order = 1, name = "Lightblossom Trinity", split = 485.9, fast = 463.8, slow = 496.9, runs = 7 },
					[3200] = { order = 2, name = "Ikuzz the Light Hunter", split = 772.0, fast = 754.9, slow = 805.7, runs = 7 },
					[3201] = { order = 3, name = "Lightwarden Ruia", split = 1149.5, fast = 1143.2, slow = 1195.2, runs = 7 },
					[3202] = { order = 4, name = "Ziekket", split = 1613.5, fast = 1590.8, slow = 1685.2, runs = 7 },
				},
			},
		},
		[585] = {
			name = "Voidscar Arena",
			levels = {
				[2] = {
					[3285] = { order = 1, name = "Taz'Rah", split = 375.7, fast = 345.3, slow = 408.6, runs = 5 },
					[3286] = { order = 2, name = "Atroxus", split = 657.6, fast = 651.2, slow = 669.3, runs = 5 },
					[3287] = { order = 3, name = "Charonus", split = 1027.6, fast = 1026.9, slow = 1042.4, runs = 5 },
				},
				[5] = {
					[3285] = { order = 1, name = "Taz'Rah", split = 406.3, fast = 368.1, slow = 443.3, runs = 6 },
					[3286] = { order = 2, name = "Atroxus", split = 695.4, fast = 626.8, slow = 740.9, runs = 6 },
					[3287] = { order = 3, name = "Charonus", split = 1041.1, fast = 989.7, slow = 1141.1, runs = 6 },
				},
				[6] = {
					[3285] = { order = 1, name = "Taz'Rah", split = 434.8, fast = 426.3, slow = 479.4, runs = 9 },
					[3286] = { order = 2, name = "Atroxus", split = 755.9, fast = 715.7, slow = 808.0, runs = 9 },
					[3287] = { order = 3, name = "Charonus", split = 1192.7, fast = 1090.4, slow = 1273.4, runs = 9 },
				},
				[7] = {
					[3285] = { order = 1, name = "Taz'Rah", split = 523.1, fast = 487.8, slow = 581.0, runs = 8 },
					[3286] = { order = 2, name = "Atroxus", split = 866.2, fast = 792.4, slow = 928.4, runs = 8 },
					[3287] = { order = 3, name = "Charonus", split = 1330.2, fast = 1240.9, slow = 1435.7, runs = 8 },
				},
				[9] = {
					[3285] = { order = 1, name = "Taz'Rah", split = 643.5, fast = 605.9, slow = 654.0, runs = 6 },
					[3286] = { order = 2, name = "Atroxus", split = 1017.3, fast = 990.5, slow = 1118.0, runs = 6 },
					[3287] = { order = 3, name = "Charonus", split = 1570.5, fast = 1497.7, slow = 1663.1, runs = 6 },
				},
				[10] = {
					[3285] = { order = 1, name = "Taz'Rah", split = 509.8, fast = 477.5, slow = 570.0, runs = 66 },
					[3286] = { order = 2, name = "Atroxus", split = 878.2, fast = 805.0, slow = 992.7, runs = 66 },
					[3287] = { order = 3, name = "Charonus", split = 1361.7, fast = 1251.1, slow = 1528.7, runs = 66 },
				},
				[11] = {
					[3285] = { order = 1, name = "Taz'Rah", split = 566.4, fast = 498.6, slow = 637.6, runs = 18 },
					[3286] = { order = 2, name = "Atroxus", split = 945.7, fast = 899.8, slow = 1075.5, runs = 18 },
					[3287] = { order = 3, name = "Charonus", split = 1610.8, fast = 1530.5, slow = 1669.1, runs = 18 },
				},
				[12] = {
					[3285] = { order = 1, name = "Taz'Rah", split = 558.0, fast = 515.2, slow = 611.8, runs = 37 },
					[3286] = { order = 2, name = "Atroxus", split = 951.6, fast = 911.7, slow = 1055.1, runs = 38 },
					[3287] = { order = 3, name = "Charonus", split = 1518.9, fast = 1398.2, slow = 1656.1, runs = 38 },
				},
				[13] = {
					[3285] = { order = 1, name = "Taz'Rah", split = 594.0, fast = 561.5, slow = 618.3, runs = 10 },
					[3286] = { order = 2, name = "Atroxus", split = 1021.1, fast = 958.9, slow = 1056.1, runs = 10 },
					[3287] = { order = 3, name = "Charonus", split = 1614.3, fast = 1519.0, slow = 1666.8, runs = 10 },
				},
				[14] = {
					[3285] = { order = 1, name = "Taz'Rah", split = 571.6, fast = 530.7, slow = 588.5, runs = 9 },
					[3286] = { order = 2, name = "Atroxus", split = 970.5, fast = 922.6, slow = 1004.8, runs = 9 },
					[3287] = { order = 3, name = "Charonus", split = 1511.2, fast = 1457.7, slow = 1670.7, runs = 9 },
				},
				[15] = {
					[3285] = { order = 1, name = "Taz'Rah", split = 603.7, fast = 551.0, slow = 639.0, runs = 6 },
					[3286] = { order = 2, name = "Atroxus", split = 994.3, fast = 957.8, slow = 1108.0, runs = 6 },
					[3287] = { order = 3, name = "Charonus", split = 1620.7, fast = 1477.0, slow = 1715.7, runs = 6 },
				},
			},
		},
		[586] = {
			name = "Den of Nalorakk",
			levels = {
				[2] = {
					[3207] = { order = 1, name = "The Hoardmonger", split = 431.4, fast = 366.1, slow = 450.9, runs = 8 },
					[3208] = { order = 2, name = "Sentinel of Winter", split = 914.0, fast = 791.4, slow = 948.1, runs = 8 },
					[3209] = { order = 3, name = "Nalorakk", split = 1298.2, fast = 1116.5, slow = 1324.4, runs = 8 },
				},
				[7] = {
					[3207] = { order = 1, name = "The Hoardmonger", split = 545.3, fast = 471.7, slow = 549.1, runs = 5 },
					[3208] = { order = 2, name = "Sentinel of Winter", split = 1049.9, fast = 963.0, slow = 1065.3, runs = 5 },
					[3209] = { order = 3, name = "Nalorakk", split = 1513.0, fast = 1390.7, slow = 1513.8, runs = 5 },
				},
				[8] = {
					[3207] = { order = 1, name = "The Hoardmonger", split = 545.5, fast = 508.3, slow = 616.7, runs = 11 },
					[3208] = { order = 2, name = "Sentinel of Winter", split = 1260.8, fast = 1172.4, slow = 1282.4, runs = 11 },
					[3209] = { order = 3, name = "Nalorakk", split = 1762.0, fast = 1635.2, slow = 1796.3, runs = 11 },
				},
				[9] = {
					[3207] = { order = 1, name = "The Hoardmonger", split = 499.3, fast = 471.1, slow = 539.6, runs = 7 },
					[3208] = { order = 2, name = "Sentinel of Winter", split = 1040.9, fast = 938.8, slow = 1132.0, runs = 8 },
					[3209] = { order = 3, name = "Nalorakk", split = 1490.4, fast = 1372.8, slow = 1635.5, runs = 8 },
				},
				[10] = {
					[3207] = { order = 1, name = "The Hoardmonger", split = 518.7, fast = 471.0, slow = 570.5, runs = 74 },
					[3208] = { order = 2, name = "Sentinel of Winter", split = 1106.2, fast = 997.0, slow = 1215.8, runs = 75 },
					[3209] = { order = 3, name = "Nalorakk", split = 1585.2, fast = 1443.3, slow = 1752.8, runs = 76 },
				},
				[11] = {
					[3207] = { order = 1, name = "The Hoardmonger", split = 531.1, fast = 477.9, slow = 650.2, runs = 17 },
					[3208] = { order = 2, name = "Sentinel of Winter", split = 1152.3, fast = 1009.4, slow = 1371.8, runs = 19 },
					[3209] = { order = 3, name = "Nalorakk", split = 1748.9, fast = 1478.4, slow = 2009.1, runs = 19 },
				},
				[12] = {
					[3207] = { order = 1, name = "The Hoardmonger", split = 555.9, fast = 495.4, slow = 587.9, runs = 35 },
					[3208] = { order = 2, name = "Sentinel of Winter", split = 1144.8, fast = 1085.3, slow = 1248.5, runs = 35 },
					[3209] = { order = 3, name = "Nalorakk", split = 1693.7, fast = 1580.0, slow = 1807.4, runs = 35 },
				},
				[13] = {
					[3207] = { order = 1, name = "The Hoardmonger", split = 552.0, fast = 510.1, slow = 584.4, runs = 11 },
					[3208] = { order = 2, name = "Sentinel of Winter", split = 1155.2, fast = 1087.5, slow = 1211.4, runs = 11 },
					[3209] = { order = 3, name = "Nalorakk", split = 1666.7, fast = 1578.9, slow = 1724.6, runs = 11 },
				},
				[14] = {
					[3207] = { order = 1, name = "The Hoardmonger", split = 564.9, fast = 520.6, slow = 632.7, runs = 12 },
					[3208] = { order = 2, name = "Sentinel of Winter", split = 1166.6, fast = 1113.0, slow = 1252.4, runs = 12 },
					[3209] = { order = 3, name = "Nalorakk", split = 1692.5, fast = 1658.9, slow = 1807.2, runs = 12 },
				},
				[15] = {
					[3207] = { order = 1, name = "The Hoardmonger", split = 544.6, fast = 492.7, slow = 574.1, runs = 10 },
					[3208] = { order = 2, name = "Sentinel of Winter", split = 1201.5, fast = 1144.5, slow = 1247.1, runs = 10 },
					[3209] = { order = 3, name = "Nalorakk", split = 1747.4, fast = 1684.3, slow = 1792.3, runs = 10 },
				},
			},
		},
		[587] = {
			name = "Murder Row",
			levels = {
				[2] = {
					[3101] = { order = 0, name = "Kystia Manaheart", split = 380.3, fast = 356.2, slow = 416.9, runs = 5 },
					[3102] = { order = 1, name = "Zaen Bladesorrow", split = 594.8, fast = 588.7, slow = 673.2, runs = 5 },
					[3103] = { order = 3, name = "Xathuux the Annihilator", split = 924.4, fast = 854.8, slow = 947.3, runs = 5 },
					[3105] = { order = 4, name = "Lithiel Cinderfury", split = 1239.3, fast = 1213.8, slow = 1292.0, runs = 5 },
				},
				[6] = {
					[3101] = { order = 0, name = "Kystia Manaheart", split = 322.1, fast = 312.5, slow = 327.6, runs = 5 },
					[3102] = { order = 1, name = "Zaen Bladesorrow", split = 534.7, fast = 529.2, slow = 542.3, runs = 5 },
					[3103] = { order = 3, name = "Xathuux the Annihilator", split = 820.3, fast = 815.9, slow = 832.0, runs = 5 },
					[3105] = { order = 4, name = "Lithiel Cinderfury", split = 1156.4, fast = 1111.6, slow = 1236.1, runs = 5 },
				},
				[7] = {
					[3101] = { order = 0, name = "Kystia Manaheart", split = 499.2, fast = 486.0, slow = 549.9, runs = 7 },
					[3102] = { order = 1, name = "Zaen Bladesorrow", split = 766.9, fast = 759.9, slow = 848.3, runs = 7 },
					[3103] = { order = 3, name = "Xathuux the Annihilator", split = 1181.0, fast = 1145.0, slow = 1261.7, runs = 7 },
					[3105] = { order = 4, name = "Lithiel Cinderfury", split = 1715.2, fast = 1610.3, slow = 1858.0, runs = 7 },
				},
				[8] = {
					[3101] = { order = 0, name = "Kystia Manaheart", split = 414.9, fast = 396.6, slow = 448.0, runs = 8 },
					[3102] = { order = 1, name = "Zaen Bladesorrow", split = 635.4, fast = 602.2, slow = 680.2, runs = 8 },
					[3103] = { order = 3, name = "Xathuux the Annihilator", split = 965.9, fast = 899.9, slow = 1054.8, runs = 8 },
					[3105] = { order = 4, name = "Lithiel Cinderfury", split = 1371.6, fast = 1242.0, slow = 1470.5, runs = 8 },
				},
				[9] = {
					[3101] = { order = 0, name = "Kystia Manaheart", split = 465.7, fast = 397.5, slow = 527.3, runs = 18 },
					[3102] = { order = 1, name = "Zaen Bladesorrow", split = 714.8, fast = 619.4, slow = 816.8, runs = 18 },
					[3103] = { order = 3, name = "Xathuux the Annihilator", split = 1104.0, fast = 976.4, slow = 1232.6, runs = 18 },
					[3105] = { order = 4, name = "Lithiel Cinderfury", split = 1497.4, fast = 1378.9, slow = 1745.2, runs = 18 },
				},
				[10] = {
					[3101] = { order = 0, name = "Kystia Manaheart", split = 443.3, fast = 399.0, slow = 518.2, runs = 92 },
					[3102] = { order = 1, name = "Zaen Bladesorrow", split = 710.0, fast = 647.9, slow = 825.1, runs = 92 },
					[3103] = { order = 3, name = "Xathuux the Annihilator", split = 1111.9, fast = 994.0, slow = 1258.8, runs = 92 },
					[3105] = { order = 4, name = "Lithiel Cinderfury", split = 1561.0, fast = 1373.7, slow = 1760.6, runs = 92 },
				},
				[11] = {
					[3101] = { order = 0, name = "Kystia Manaheart", split = 471.2, fast = 424.5, slow = 538.0, runs = 39 },
					[3102] = { order = 1, name = "Zaen Bladesorrow", split = 753.8, fast = 682.8, slow = 835.2, runs = 39 },
					[3103] = { order = 3, name = "Xathuux the Annihilator", split = 1151.9, fast = 1030.5, slow = 1306.3, runs = 39 },
					[3105] = { order = 4, name = "Lithiel Cinderfury", split = 1621.4, fast = 1427.7, slow = 1843.1, runs = 40 },
				},
				[12] = {
					[3101] = { order = 0, name = "Kystia Manaheart", split = 470.5, fast = 418.7, slow = 522.3, runs = 44 },
					[3102] = { order = 1, name = "Zaen Bladesorrow", split = 743.3, fast = 681.6, slow = 803.4, runs = 45 },
					[3103] = { order = 3, name = "Xathuux the Annihilator", split = 1167.7, fast = 1094.3, slow = 1245.8, runs = 45 },
					[3105] = { order = 4, name = "Lithiel Cinderfury", split = 1676.0, fast = 1566.1, slow = 1798.6, runs = 45 },
				},
				[13] = {
					[3101] = { order = 0, name = "Kystia Manaheart", split = 460.2, fast = 439.3, slow = 502.9, runs = 12 },
					[3102] = { order = 1, name = "Zaen Bladesorrow", split = 763.4, fast = 718.3, slow = 828.2, runs = 12 },
					[3103] = { order = 3, name = "Xathuux the Annihilator", split = 1268.3, fast = 1145.3, slow = 1313.6, runs = 12 },
					[3105] = { order = 4, name = "Lithiel Cinderfury", split = 1851.4, fast = 1651.7, slow = 1964.1, runs = 12 },
				},
				[14] = {
					[3101] = { order = 0, name = "Kystia Manaheart", split = 501.6, fast = 476.3, slow = 560.3, runs = 15 },
					[3102] = { order = 1, name = "Zaen Bladesorrow", split = 782.2, fast = 747.5, slow = 902.2, runs = 15 },
					[3103] = { order = 3, name = "Xathuux the Annihilator", split = 1246.7, fast = 1220.6, slow = 1412.9, runs = 15 },
					[3105] = { order = 4, name = "Lithiel Cinderfury", split = 1818.3, fast = 1682.4, slow = 1974.0, runs = 15 },
				},
				[15] = {
					[3101] = { order = 0, name = "Kystia Manaheart", split = 508.0, fast = 484.0, slow = 516.5, runs = 5 },
					[3102] = { order = 1, name = "Zaen Bladesorrow", split = 785.0, fast = 777.0, slow = 838.9, runs = 5 },
					[3103] = { order = 3, name = "Xathuux the Annihilator", split = 1324.1, fast = 1259.4, slow = 1337.3, runs = 5 },
					[3105] = { order = 4, name = "Lithiel Cinderfury", split = 1885.8, fast = 1837.4, slow = 1886.4, runs = 5 },
				},
				[16] = {
					[3101] = { order = 0, name = "Kystia Manaheart", split = 508.8, fast = 468.4, slow = 523.4, runs = 6 },
					[3102] = { order = 1, name = "Zaen Bladesorrow", split = 779.8, fast = 752.3, slow = 822.9, runs = 6 },
					[3103] = { order = 3, name = "Xathuux the Annihilator", split = 1269.9, fast = 1253.8, slow = 1353.8, runs = 6 },
					[3105] = { order = 4, name = "Lithiel Cinderfury", split = 1870.0, fast = 1746.9, slow = 1905.5, runs = 6 },
				},
			},
		},
		[588] = {
			name = "Altar of Fangs",
			levels = {
				[5] = {
					[3456] = { order = 1, name = "Rav'i", split = 441.6, fast = 398.3, slow = 465.9, runs = 6 },
					[3457] = { order = 2, name = "The Writhing Coil", split = 719.5, fast = 653.3, slow = 778.5, runs = 6 },
					[3458] = { order = 3, name = "Zul'jan", split = 1149.2, fast = 1055.9, slow = 1254.3, runs = 6 },
				},
				[6] = {
					[3456] = { order = 1, name = "Rav'i", split = 511.1, fast = 434.7, slow = 524.4, runs = 9 },
					[3457] = { order = 2, name = "The Writhing Coil", split = 818.0, fast = 740.8, slow = 863.0, runs = 9 },
					[3458] = { order = 3, name = "Zul'jan", split = 1314.7, fast = 1160.4, slow = 1391.4, runs = 9 },
				},
				[7] = {
					[3456] = { order = 1, name = "Rav'i", split = 466.4, fast = 410.2, slow = 494.4, runs = 5 },
					[3457] = { order = 2, name = "The Writhing Coil", split = 752.2, fast = 688.4, slow = 842.5, runs = 5 },
					[3458] = { order = 3, name = "Zul'jan", split = 1201.5, fast = 1130.0, slow = 1354.4, runs = 5 },
				},
				[8] = {
					[3456] = { order = 1, name = "Rav'i", split = 510.6, fast = 468.7, slow = 551.7, runs = 10 },
					[3457] = { order = 2, name = "The Writhing Coil", split = 842.9, fast = 795.0, slow = 909.5, runs = 10 },
					[3458] = { order = 3, name = "Zul'jan", split = 1364.6, fast = 1321.0, slow = 1480.2, runs = 10 },
				},
				[9] = {
					[3456] = { order = 1, name = "Rav'i", split = 539.8, fast = 477.2, slow = 559.2, runs = 10 },
					[3457] = { order = 2, name = "The Writhing Coil", split = 863.4, fast = 834.9, slow = 904.7, runs = 10 },
					[3458] = { order = 3, name = "Zul'jan", split = 1372.6, fast = 1339.3, slow = 1415.3, runs = 10 },
				},
				[10] = {
					[3456] = { order = 1, name = "Rav'i", split = 564.0, fast = 514.6, slow = 635.0, runs = 71 },
					[3457] = { order = 2, name = "The Writhing Coil", split = 956.3, fast = 853.1, slow = 1076.0, runs = 71 },
					[3458] = { order = 3, name = "Zul'jan", split = 1507.1, fast = 1377.1, slow = 1688.9, runs = 71 },
				},
				[11] = {
					[3456] = { order = 1, name = "Rav'i", split = 581.1, fast = 552.5, slow = 632.2, runs = 24 },
					[3457] = { order = 2, name = "The Writhing Coil", split = 965.2, fast = 917.9, slow = 1036.0, runs = 24 },
					[3458] = { order = 3, name = "Zul'jan", split = 1545.3, fast = 1445.8, slow = 1661.7, runs = 25 },
				},
				[12] = {
					[3456] = { order = 1, name = "Rav'i", split = 595.0, fast = 573.4, slow = 683.1, runs = 46 },
					[3457] = { order = 2, name = "The Writhing Coil", split = 1013.7, fast = 933.7, slow = 1102.2, runs = 46 },
					[3458] = { order = 3, name = "Zul'jan", split = 1584.0, fast = 1478.9, slow = 1721.7, runs = 46 },
				},
				[13] = {
					[3456] = { order = 1, name = "Rav'i", split = 633.3, fast = 594.4, slow = 688.5, runs = 21 },
					[3457] = { order = 2, name = "The Writhing Coil", split = 1029.0, fast = 989.3, slow = 1089.8, runs = 21 },
					[3458] = { order = 3, name = "Zul'jan", split = 1656.0, fast = 1596.6, slow = 1730.6, runs = 21 },
				},
				[14] = {
					[3456] = { order = 1, name = "Rav'i", split = 657.3, fast = 623.3, slow = 673.5, runs = 13 },
					[3457] = { order = 2, name = "The Writhing Coil", split = 1071.2, fast = 1038.1, slow = 1123.3, runs = 13 },
					[3458] = { order = 3, name = "Zul'jan", split = 1727.5, fast = 1631.8, slow = 1772.4, runs = 13 },
				},
				[15] = {
					[3456] = { order = 1, name = "Rav'i", split = 666.6, fast = 617.5, slow = 702.8, runs = 18 },
					[3457] = { order = 2, name = "The Writhing Coil", split = 1092.6, fast = 1047.2, slow = 1169.1, runs = 18 },
					[3458] = { order = 3, name = "Zul'jan", split = 1737.4, fast = 1675.0, slow = 1800.1, runs = 18 },
				},
			},
		},
	},
}
