local _, addonTable = ...

-- Benchmark boss splits for PeaversSplits.
--
-- A SPLIT is the time from the start of a keystone run to a boss dying. For
-- each dungeon and each exact keystone level this holds what the middle of
-- the pool does at every boss, so a running key can be told how far ahead or
-- behind it is while there is still something to do about it.
--
-- Schema:
--   updated   = "YYYY-MM-DD HH:MM:SS" (UTC)
--   partition = the game patch these pools were built on, "major.minor"
--   dungeons  = [mapChallengeModeID].levels[keystoneLevel][DungeonEncounterID]
--             = { order, name, split, fast, slow, runs }
--
-- `split` is the pool's median, `fast`/`slow` its p25/p75, all in SECONDS
-- from the start of the run. `runs` is the sample the figures rest on and is
-- per boss, not per level: a depleted run that ended at the third boss counts
-- toward the first two and not the last.
--
-- EXACT keystone level, never a band. Enemy health scales per level, so a
-- +19 is genuinely slower than a +10 for reasons that are not the group's
-- doing, and a level with no entry means no pool cleared the sample floor -
-- not that the run cannot be measured. Consumers must say so rather than
-- reaching for a neighbouring level.
--
-- ONE PARTITION ONLY. Every dungeon here was keyed on the same patch, so
-- nothing in this file can be compared against a pool from another one. A
-- dungeon rotated out of the current season simply has no entry.
--
-- Auto-generated by splits-module (PeaversAddonDataSupplier) from
-- parses.gg /api/keys/{id}/splits. Do not edit by hand.
addonTable.SplitsData = {
	updated = "2026-09-27 05:00:46",
	partition = "12.1",

	dungeons = {
		[249] = {
			name = "Kings' Rest",
			levels = {
				[5] = {
					[2139] = { order = 1, name = "The Golden Serpent", split = 302.7, fast = 264.3, slow = 321.3, runs = 6 },
					[2142] = { order = 2, name = "Mchimba the Embalmer", split = 777.2, fast = 710.8, slow = 804.3, runs = 6 },
					[2140] = { order = 3, name = "The Council of Tribes", split = 1135.2, fast = 990.4, slow = 1199.9, runs = 6 },
					[2143] = { order = 4, name = "Dazar, The First King", split = 1370.8, fast = 1244.2, slow = 1423.2, runs = 6 },
				},
				[7] = {
					[2139] = { order = 1, name = "The Golden Serpent", split = 315.0, fast = 302.9, slow = 351.9, runs = 14 },
					[2142] = { order = 2, name = "Mchimba the Embalmer", split = 910.8, fast = 793.9, slow = 959.4, runs = 14 },
					[2140] = { order = 3, name = "The Council of Tribes", split = 1265.2, fast = 1139.5, slow = 1321.0, runs = 14 },
					[2143] = { order = 4, name = "Dazar, The First King", split = 1531.3, fast = 1355.7, slow = 1602.1, runs = 14 },
				},
				[8] = {
					[2139] = { order = 1, name = "The Golden Serpent", split = 311.7, fast = 280.5, slow = 348.4, runs = 10 },
					[2142] = { order = 2, name = "Mchimba the Embalmer", split = 800.8, fast = 783.7, slow = 930.2, runs = 10 },
					[2140] = { order = 3, name = "The Council of Tribes", split = 1128.9, fast = 1100.3, slow = 1306.2, runs = 10 },
					[2143] = { order = 4, name = "Dazar, The First King", split = 1334.8, fast = 1326.5, slow = 1532.7, runs = 10 },
				},
				[9] = {
					[2139] = { order = 1, name = "The Golden Serpent", split = 393.8, fast = 356.6, slow = 439.4, runs = 10 },
					[2142] = { order = 2, name = "Mchimba the Embalmer", split = 967.4, fast = 946.6, slow = 1023.7, runs = 10 },
					[2140] = { order = 3, name = "The Council of Tribes", split = 1359.2, fast = 1329.2, slow = 1428.4, runs = 10 },
					[2143] = { order = 4, name = "Dazar, The First King", split = 1602.6, fast = 1588.1, slow = 1684.3, runs = 10 },
				},
				[10] = {
					[2139] = { order = 1, name = "The Golden Serpent", split = 363.7, fast = 316.6, slow = 395.2, runs = 64 },
					[2142] = { order = 2, name = "Mchimba the Embalmer", split = 912.6, fast = 827.3, slow = 1015.0, runs = 65 },
					[2140] = { order = 3, name = "The Council of Tribes", split = 1293.9, fast = 1185.3, slow = 1430.8, runs = 65 },
					[2143] = { order = 4, name = "Dazar, The First King", split = 1563.6, fast = 1430.9, slow = 1745.1, runs = 65 },
				},
				[11] = {
					[2139] = { order = 1, name = "The Golden Serpent", split = 383.4, fast = 340.7, slow = 422.0, runs = 20 },
					[2142] = { order = 2, name = "Mchimba the Embalmer", split = 939.1, fast = 855.4, slow = 1033.8, runs = 20 },
					[2140] = { order = 3, name = "The Council of Tribes", split = 1346.6, fast = 1259.5, slow = 1492.0, runs = 20 },
					[2143] = { order = 4, name = "Dazar, The First King", split = 1629.5, fast = 1513.0, slow = 1789.1, runs = 20 },
				},
				[12] = {
					[2139] = { order = 1, name = "The Golden Serpent", split = 377.7, fast = 343.7, slow = 404.2, runs = 37 },
					[2142] = { order = 2, name = "Mchimba the Embalmer", split = 967.6, fast = 898.0, slow = 1021.2, runs = 38 },
					[2140] = { order = 3, name = "The Council of Tribes", split = 1368.1, fast = 1292.0, slow = 1485.8, runs = 38 },
					[2143] = { order = 4, name = "Dazar, The First King", split = 1647.7, fast = 1558.0, slow = 1784.4, runs = 38 },
				},
				[13] = {
					[2139] = { order = 1, name = "The Golden Serpent", split = 376.9, fast = 361.9, slow = 401.5, runs = 11 },
					[2142] = { order = 2, name = "Mchimba the Embalmer", split = 1010.5, fast = 950.5, slow = 1047.8, runs = 11 },
					[2140] = { order = 3, name = "The Council of Tribes", split = 1428.6, fast = 1375.7, slow = 1502.5, runs = 11 },
					[2143] = { order = 4, name = "Dazar, The First King", split = 1775.7, fast = 1659.8, slow = 1848.0, runs = 11 },
				},
				[14] = {
					[2139] = { order = 1, name = "The Golden Serpent", split = 376.7, fast = 362.1, slow = 391.1, runs = 8 },
					[2142] = { order = 2, name = "Mchimba the Embalmer", split = 1015.3, fast = 971.4, slow = 1065.3, runs = 8 },
					[2140] = { order = 3, name = "The Council of Tribes", split = 1480.6, fast = 1432.0, slow = 1509.7, runs = 9 },
					[2143] = { order = 4, name = "Dazar, The First King", split = 1760.4, fast = 1721.0, slow = 1810.4, runs = 9 },
				},
				[15] = {
					[2139] = { order = 1, name = "The Golden Serpent", split = 381.9, fast = 378.0, slow = 432.9, runs = 12 },
					[2142] = { order = 2, name = "Mchimba the Embalmer", split = 1071.3, fast = 1003.7, slow = 1087.3, runs = 12 },
					[2140] = { order = 3, name = "The Council of Tribes", split = 1515.5, fast = 1475.6, slow = 1558.7, runs = 12 },
					[2143] = { order = 4, name = "Dazar, The First King", split = 1830.6, fast = 1776.9, slow = 1884.1, runs = 12 },
				},
				[16] = {
					[2139] = { order = 1, name = "The Golden Serpent", split = 412.1, fast = 400.5, slow = 419.3, runs = 5 },
					[2142] = { order = 2, name = "Mchimba the Embalmer", split = 1069.0, fast = 1052.4, slow = 1117.7, runs = 5 },
					[2140] = { order = 3, name = "The Council of Tribes", split = 1595.2, fast = 1551.9, slow = 1812.3, runs = 5 },
					[2143] = { order = 4, name = "Dazar, The First King", split = 1908.4, fast = 1849.8, slow = 2193.4, runs = 5 },
				},
			},
		},
		[250] = {
			name = "Temple of Sethraliss",
			levels = {
				[2] = {
					[2124] = { order = 1, name = "Adderis and Aspix", split = 238.3, fast = 198.2, slow = 247.2, runs = 7 },
					[2125] = { order = 2, name = "Merektha", split = 596.9, fast = 470.7, slow = 627.9, runs = 7 },
					[2126] = { order = 3, name = "Galvazzt", split = 817.0, fast = 685.1, slow = 865.3, runs = 7 },
					[2127] = { order = 4, name = "Avatar of Sethraliss", split = 1209.3, fast = 1067.0, slow = 1267.3, runs = 7 },
				},
				[6] = {
					[2124] = { order = 1, name = "Adderis and Aspix", split = 247.8, fast = 216.4, slow = 265.7, runs = 6 },
					[2125] = { order = 2, name = "Merektha", split = 645.5, fast = 514.3, slow = 731.4, runs = 6 },
					[2126] = { order = 3, name = "Galvazzt", split = 862.1, fast = 706.9, slow = 977.0, runs = 6 },
					[2127] = { order = 4, name = "Avatar of Sethraliss", split = 1373.3, fast = 1249.0, slow = 1669.2, runs = 6 },
				},
				[7] = {
					[2124] = { order = 1, name = "Adderis and Aspix", split = 300.4, fast = 252.1, slow = 336.3, runs = 6 },
					[2125] = { order = 2, name = "Merektha", split = 737.1, fast = 661.7, slow = 846.8, runs = 6 },
					[2126] = { order = 3, name = "Galvazzt", split = 1046.2, fast = 939.3, slow = 1181.9, runs = 6 },
					[2127] = { order = 4, name = "Avatar of Sethraliss", split = 1692.5, fast = 1464.0, slow = 1751.0, runs = 6 },
				},
				[8] = {
					[2124] = { order = 1, name = "Adderis and Aspix", split = 257.8, fast = 253.2, slow = 262.5, runs = 6 },
					[2125] = { order = 2, name = "Merektha", split = 647.1, fast = 607.0, slow = 676.0, runs = 6 },
					[2126] = { order = 3, name = "Galvazzt", split = 891.3, fast = 844.6, slow = 944.2, runs = 6 },
					[2127] = { order = 4, name = "Avatar of Sethraliss", split = 1348.3, fast = 1280.5, slow = 1391.6, runs = 6 },
				},
				[9] = {
					[2124] = { order = 1, name = "Adderis and Aspix", split = 298.7, fast = 275.1, slow = 316.5, runs = 14 },
					[2125] = { order = 2, name = "Merektha", split = 756.4, fast = 707.6, slow = 799.4, runs = 14 },
					[2126] = { order = 3, name = "Galvazzt", split = 1053.7, fast = 984.5, slow = 1119.5, runs = 14 },
					[2127] = { order = 4, name = "Avatar of Sethraliss", split = 1555.2, fast = 1471.9, slow = 1601.1, runs = 14 },
				},
				[10] = {
					[2124] = { order = 1, name = "Adderis and Aspix", split = 298.5, fast = 264.5, slow = 333.9, runs = 71 },
					[2125] = { order = 2, name = "Merektha", split = 768.3, fast = 665.0, slow = 867.3, runs = 71 },
					[2126] = { order = 3, name = "Galvazzt", split = 1072.3, fast = 933.3, slow = 1191.4, runs = 71 },
					[2127] = { order = 4, name = "Avatar of Sethraliss", split = 1560.1, fast = 1374.6, slow = 1723.5, runs = 71 },
				},
				[11] = {
					[2124] = { order = 1, name = "Adderis and Aspix", split = 299.6, fast = 292.7, slow = 319.1, runs = 17 },
					[2125] = { order = 2, name = "Merektha", split = 809.3, fast = 773.8, slow = 878.7, runs = 17 },
					[2126] = { order = 3, name = "Galvazzt", split = 1142.1, fast = 1069.6, slow = 1264.3, runs = 17 },
					[2127] = { order = 4, name = "Avatar of Sethraliss", split = 1599.7, fast = 1477.5, slow = 1806.6, runs = 17 },
				},
				[12] = {
					[2124] = { order = 1, name = "Adderis and Aspix", split = 298.9, fast = 277.6, slow = 323.9, runs = 40 },
					[2125] = { order = 2, name = "Merektha", split = 772.8, fast = 744.6, slow = 832.5, runs = 40 },
					[2126] = { order = 3, name = "Galvazzt", split = 1077.4, fast = 1043.9, slow = 1176.7, runs = 40 },
					[2127] = { order = 4, name = "Avatar of Sethraliss", split = 1570.1, fast = 1476.7, slow = 1705.1, runs = 40 },
				},
				[13] = {
					[2124] = { order = 1, name = "Adderis and Aspix", split = 313.3, fast = 288.8, slow = 339.1, runs = 16 },
					[2125] = { order = 2, name = "Merektha", split = 813.3, fast = 758.3, slow = 872.1, runs = 17 },
					[2126] = { order = 3, name = "Galvazzt", split = 1163.6, fast = 1085.1, slow = 1252.3, runs = 17 },
					[2127] = { order = 4, name = "Avatar of Sethraliss", split = 1612.9, fast = 1521.1, slow = 1754.5, runs = 17 },
				},
				[14] = {
					[2124] = { order = 1, name = "Adderis and Aspix", split = 331.9, fast = 320.7, slow = 336.7, runs = 7 },
					[2125] = { order = 2, name = "Merektha", split = 841.1, fast = 819.6, slow = 923.9, runs = 7 },
					[2126] = { order = 3, name = "Galvazzt", split = 1193.7, fast = 1169.4, slow = 1295.3, runs = 7 },
					[2127] = { order = 4, name = "Avatar of Sethraliss", split = 1714.9, fast = 1574.3, slow = 1790.4, runs = 7 },
				},
				[15] = {
					[2124] = { order = 1, name = "Adderis and Aspix", split = 336.5, fast = 327.6, slow = 373.0, runs = 10 },
					[2125] = { order = 2, name = "Merektha", split = 930.6, fast = 886.7, slow = 963.6, runs = 10 },
					[2126] = { order = 3, name = "Galvazzt", split = 1304.3, fast = 1224.8, slow = 1333.7, runs = 10 },
					[2127] = { order = 4, name = "Avatar of Sethraliss", split = 1745.0, fast = 1669.7, slow = 1821.7, runs = 10 },
				},
				[16] = {
					[2124] = { order = 1, name = "Adderis and Aspix", split = 330.5, fast = 318.8, slow = 346.1, runs = 6 },
					[2125] = { order = 2, name = "Merektha", split = 873.4, fast = 860.6, slow = 959.1, runs = 6 },
					[2126] = { order = 3, name = "Galvazzt", split = 1252.4, fast = 1221.7, slow = 1325.2, runs = 6 },
					[2127] = { order = 4, name = "Avatar of Sethraliss", split = 1776.5, fast = 1751.4, slow = 1804.2, runs = 6 },
				},
			},
		},
		[399] = {
			name = "Ruby Life Pools",
			levels = {
				[2] = {
					[2609] = { order = 1, name = "Melidrussa Chillworn", split = 263.8, fast = 247.6, slow = 317.4, runs = 9 },
					[2606] = { order = 2, name = "Kokia Blazehoof", split = 659.6, fast = 622.5, slow = 824.6, runs = 9 },
					[2623] = { order = 3, name = "Kyrakka and Erkhart Stormvein", split = 879.4, fast = 805.1, slow = 1091.6, runs = 9 },
				},
				[4] = {
					[2609] = { order = 1, name = "Melidrussa Chillworn", split = 359.6, fast = 330.0, slow = 378.5, runs = 5 },
					[2606] = { order = 2, name = "Kokia Blazehoof", split = 893.8, fast = 806.7, slow = 937.8, runs = 5 },
					[2623] = { order = 3, name = "Kyrakka and Erkhart Stormvein", split = 1216.4, fast = 1096.7, slow = 1281.5, runs = 5 },
				},
				[7] = {
					[2609] = { order = 1, name = "Melidrussa Chillworn", split = 400.3, fast = 376.8, slow = 437.4, runs = 8 },
					[2606] = { order = 2, name = "Kokia Blazehoof", split = 1020.4, fast = 895.7, slow = 1119.8, runs = 8 },
					[2623] = { order = 3, name = "Kyrakka and Erkhart Stormvein", split = 1336.5, fast = 1211.7, slow = 1459.8, runs = 8 },
				},
				[8] = {
					[2609] = { order = 1, name = "Melidrussa Chillworn", split = 392.8, fast = 366.6, slow = 418.6, runs = 16 },
					[2606] = { order = 2, name = "Kokia Blazehoof", split = 978.6, fast = 932.6, slow = 1121.7, runs = 16 },
					[2623] = { order = 3, name = "Kyrakka and Erkhart Stormvein", split = 1331.5, fast = 1259.7, slow = 1503.5, runs = 16 },
				},
				[9] = {
					[2609] = { order = 1, name = "Melidrussa Chillworn", split = 354.0, fast = 339.7, slow = 393.8, runs = 6 },
					[2606] = { order = 2, name = "Kokia Blazehoof", split = 904.7, fast = 862.0, slow = 1003.1, runs = 6 },
					[2623] = { order = 3, name = "Kyrakka and Erkhart Stormvein", split = 1218.9, fast = 1171.4, slow = 1306.2, runs = 6 },
				},
				[10] = {
					[2609] = { order = 1, name = "Melidrussa Chillworn", split = 405.5, fast = 370.0, slow = 431.3, runs = 59 },
					[2606] = { order = 2, name = "Kokia Blazehoof", split = 1008.3, fast = 907.9, slow = 1091.0, runs = 59 },
					[2623] = { order = 3, name = "Kyrakka and Erkhart Stormvein", split = 1332.9, fast = 1245.0, slow = 1526.1, runs = 59 },
				},
				[11] = {
					[2609] = { order = 1, name = "Melidrussa Chillworn", split = 429.9, fast = 406.1, slow = 458.1, runs = 18 },
					[2606] = { order = 2, name = "Kokia Blazehoof", split = 1097.8, fast = 1002.2, slow = 1190.8, runs = 19 },
					[2623] = { order = 3, name = "Kyrakka and Erkhart Stormvein", split = 1451.7, fast = 1373.3, slow = 1599.4, runs = 19 },
				},
				[12] = {
					[2609] = { order = 1, name = "Melidrussa Chillworn", split = 415.6, fast = 391.8, slow = 454.3, runs = 35 },
					[2606] = { order = 2, name = "Kokia Blazehoof", split = 1013.2, fast = 972.1, slow = 1107.5, runs = 36 },
					[2623] = { order = 3, name = "Kyrakka and Erkhart Stormvein", split = 1397.0, fast = 1306.3, slow = 1531.6, runs = 36 },
				},
				[13] = {
					[2609] = { order = 1, name = "Melidrussa Chillworn", split = 433.7, fast = 421.9, slow = 460.8, runs = 11 },
					[2606] = { order = 2, name = "Kokia Blazehoof", split = 1029.8, fast = 991.1, slow = 1161.5, runs = 11 },
					[2623] = { order = 3, name = "Kyrakka and Erkhart Stormvein", split = 1435.1, fast = 1376.1, slow = 1554.8, runs = 11 },
				},
				[14] = {
					[2609] = { order = 1, name = "Melidrussa Chillworn", split = 451.3, fast = 436.7, slow = 477.7, runs = 17 },
					[2606] = { order = 2, name = "Kokia Blazehoof", split = 1115.9, fast = 1085.3, slow = 1220.5, runs = 17 },
					[2623] = { order = 3, name = "Kyrakka and Erkhart Stormvein", split = 1538.1, fast = 1506.8, slow = 1647.2, runs = 17 },
				},
				[15] = {
					[2609] = { order = 1, name = "Melidrussa Chillworn", split = 437.8, fast = 422.9, slow = 449.0, runs = 11 },
					[2606] = { order = 2, name = "Kokia Blazehoof", split = 1104.3, fast = 1059.9, slow = 1148.0, runs = 11 },
					[2623] = { order = 3, name = "Kyrakka and Erkhart Stormvein", split = 1492.7, fast = 1464.2, slow = 1550.1, runs = 11 },
				},
				[16] = {
					[2609] = { order = 1, name = "Melidrussa Chillworn", split = 466.2, fast = 456.6, slow = 481.5, runs = 6 },
					[2606] = { order = 2, name = "Kokia Blazehoof", split = 1142.8, fast = 1130.2, slow = 1199.2, runs = 6 },
					[2623] = { order = 3, name = "Kyrakka and Erkhart Stormvein", split = 1588.0, fast = 1542.8, slow = 1627.6, runs = 6 },
				},
			},
		},
		[584] = {
			name = "The Blinding Vale",
			levels = {
				[5] = {
					[3199] = { order = 1, name = "Lightblossom Trinity", split = 362.3, fast = 339.0, slow = 391.9, runs = 6 },
					[3200] = { order = 2, name = "Ikuzz the Light Hunter", split = 530.4, fast = 487.9, slow = 575.6, runs = 6 },
					[3201] = { order = 3, name = "Lightwarden Ruia", split = 762.4, fast = 719.2, slow = 835.4, runs = 6 },
					[3202] = { order = 4, name = "Ziekket", split = 1060.0, fast = 994.0, slow = 1119.4, runs = 6 },
				},
				[6] = {
					[3199] = { order = 1, name = "Lightblossom Trinity", split = 389.1, fast = 387.1, slow = 408.3, runs = 5 },
					[3200] = { order = 2, name = "Ikuzz the Light Hunter", split = 629.2, fast = 588.0, slow = 636.8, runs = 5 },
					[3201] = { order = 3, name = "Lightwarden Ruia", split = 891.3, fast = 861.2, slow = 936.8, runs = 5 },
					[3202] = { order = 4, name = "Ziekket", split = 1242.6, fast = 1187.4, slow = 1349.2, runs = 5 },
				},
				[7] = {
					[3199] = { order = 1, name = "Lightblossom Trinity", split = 414.2, fast = 397.0, slow = 489.5, runs = 8 },
					[3200] = { order = 2, name = "Ikuzz the Light Hunter", split = 624.7, fast = 613.6, slow = 711.8, runs = 8 },
					[3201] = { order = 3, name = "Lightwarden Ruia", split = 914.6, fast = 884.8, slow = 1002.3, runs = 8 },
					[3202] = { order = 4, name = "Ziekket", split = 1266.0, fast = 1252.0, slow = 1417.6, runs = 8 },
				},
				[8] = {
					[3199] = { order = 1, name = "Lightblossom Trinity", split = 459.4, fast = 398.7, slow = 569.8, runs = 7 },
					[3200] = { order = 2, name = "Ikuzz the Light Hunter", split = 572.0, fast = 505.9, slow = 697.5, runs = 7 },
					[3201] = { order = 3, name = "Lightwarden Ruia", split = 1006.6, fast = 908.6, slow = 1041.6, runs = 7 },
					[3202] = { order = 4, name = "Ziekket", split = 1402.3, fast = 1283.0, slow = 1496.1, runs = 7 },
				},
				[9] = {
					[3199] = { order = 1, name = "Lightblossom Trinity", split = 426.9, fast = 381.8, slow = 488.1, runs = 12 },
					[3200] = { order = 2, name = "Ikuzz the Light Hunter", split = 628.9, fast = 607.4, slow = 744.7, runs = 12 },
					[3201] = { order = 3, name = "Lightwarden Ruia", split = 903.7, fast = 885.0, slow = 1117.1, runs = 12 },
					[3202] = { order = 4, name = "Ziekket", split = 1313.4, fast = 1275.6, slow = 1563.4, runs = 12 },
				},
				[10] = {
					[3199] = { order = 1, name = "Lightblossom Trinity", split = 445.7, fast = 411.2, slow = 525.3, runs = 66 },
					[3200] = { order = 2, name = "Ikuzz the Light Hunter", split = 709.1, fast = 629.0, slow = 777.7, runs = 66 },
					[3201] = { order = 3, name = "Lightwarden Ruia", split = 1030.5, fast = 934.6, slow = 1108.7, runs = 67 },
					[3202] = { order = 4, name = "Ziekket", split = 1500.3, fast = 1303.5, slow = 1561.1, runs = 68 },
				},
				[11] = {
					[3199] = { order = 1, name = "Lightblossom Trinity", split = 478.0, fast = 423.4, slow = 606.2, runs = 22 },
					[3200] = { order = 2, name = "Ikuzz the Light Hunter", split = 748.7, fast = 664.1, slow = 840.5, runs = 22 },
					[3201] = { order = 3, name = "Lightwarden Ruia", split = 1070.3, fast = 1024.1, slow = 1197.2, runs = 22 },
					[3202] = { order = 4, name = "Ziekket", split = 1471.1, fast = 1416.9, slow = 1701.6, runs = 22 },
				},
				[12] = {
					[3199] = { order = 1, name = "Lightblossom Trinity", split = 472.4, fast = 444.4, slow = 532.6, runs = 37 },
					[3200] = { order = 2, name = "Ikuzz the Light Hunter", split = 747.4, fast = 702.9, slow = 814.6, runs = 37 },
					[3201] = { order = 3, name = "Lightwarden Ruia", split = 1120.3, fast = 1062.2, slow = 1233.2, runs = 37 },
					[3202] = { order = 4, name = "Ziekket", split = 1631.4, fast = 1515.4, slow = 1767.4, runs = 37 },
				},
				[13] = {
					[3199] = { order = 1, name = "Lightblossom Trinity", split = 545.9, fast = 500.4, slow = 590.0, runs = 23 },
					[3200] = { order = 2, name = "Ikuzz the Light Hunter", split = 822.6, fast = 763.6, slow = 871.8, runs = 23 },
					[3201] = { order = 3, name = "Lightwarden Ruia", split = 1200.8, fast = 1143.7, slow = 1255.5, runs = 23 },
					[3202] = { order = 4, name = "Ziekket", split = 1649.4, fast = 1581.8, slow = 1754.7, runs = 23 },
				},
				[14] = {
					[3199] = { order = 1, name = "Lightblossom Trinity", split = 467.9, fast = 448.1, slow = 574.4, runs = 9 },
					[3200] = { order = 2, name = "Ikuzz the Light Hunter", split = 770.9, fast = 732.1, slow = 878.9, runs = 9 },
					[3201] = { order = 3, name = "Lightwarden Ruia", split = 1130.1, fast = 1087.2, slow = 1272.9, runs = 9 },
					[3202] = { order = 4, name = "Ziekket", split = 1613.0, fast = 1557.6, slow = 1771.8, runs = 9 },
				},
				[15] = {
					[3199] = { order = 1, name = "Lightblossom Trinity", split = 475.3, fast = 452.0, slow = 491.4, runs = 10 },
					[3200] = { order = 2, name = "Ikuzz the Light Hunter", split = 759.2, fast = 739.7, slow = 787.0, runs = 10 },
					[3201] = { order = 3, name = "Lightwarden Ruia", split = 1148.8, fast = 1100.3, slow = 1196.9, runs = 10 },
					[3202] = { order = 4, name = "Ziekket", split = 1603.8, fast = 1566.1, slow = 1678.9, runs = 10 },
				},
			},
		},
		[585] = {
			name = "Voidscar Arena",
			levels = {
				[2] = {
					[3285] = { order = 1, name = "Taz'Rah", split = 375.7, fast = 345.3, slow = 408.6, runs = 5 },
					[3286] = { order = 2, name = "Atroxus", split = 657.6, fast = 651.2, slow = 669.3, runs = 5 },
					[3287] = { order = 3, name = "Charonus", split = 1027.6, fast = 1026.9, slow = 1042.4, runs = 5 },
				},
				[5] = {
					[3285] = { order = 1, name = "Taz'Rah", split = 406.3, fast = 368.1, slow = 443.3, runs = 6 },
					[3286] = { order = 2, name = "Atroxus", split = 695.4, fast = 626.8, slow = 740.9, runs = 6 },
					[3287] = { order = 3, name = "Charonus", split = 1041.1, fast = 989.7, slow = 1141.1, runs = 6 },
				},
				[6] = {
					[3285] = { order = 1, name = "Taz'Rah", split = 434.8, fast = 426.3, slow = 479.4, runs = 9 },
					[3286] = { order = 2, name = "Atroxus", split = 755.9, fast = 715.7, slow = 808.0, runs = 9 },
					[3287] = { order = 3, name = "Charonus", split = 1192.7, fast = 1090.4, slow = 1273.4, runs = 9 },
				},
				[7] = {
					[3285] = { order = 1, name = "Taz'Rah", split = 523.1, fast = 487.8, slow = 581.0, runs = 8 },
					[3286] = { order = 2, name = "Atroxus", split = 866.2, fast = 792.4, slow = 928.4, runs = 8 },
					[3287] = { order = 3, name = "Charonus", split = 1330.2, fast = 1240.9, slow = 1435.7, runs = 8 },
				},
				[9] = {
					[3285] = { order = 1, name = "Taz'Rah", split = 643.5, fast = 605.9, slow = 654.0, runs = 6 },
					[3286] = { order = 2, name = "Atroxus", split = 1017.3, fast = 990.5, slow = 1118.0, runs = 6 },
					[3287] = { order = 3, name = "Charonus", split = 1570.5, fast = 1497.7, slow = 1663.1, runs = 6 },
				},
				[10] = {
					[3285] = { order = 1, name = "Taz'Rah", split = 512.8, fast = 477.6, slow = 573.4, runs = 72 },
					[3286] = { order = 2, name = "Atroxus", split = 880.3, fast = 801.3, slow = 997.9, runs = 72 },
					[3287] = { order = 3, name = "Charonus", split = 1370.2, fast = 1266.1, slow = 1538.6, runs = 72 },
				},
				[11] = {
					[3285] = { order = 1, name = "Taz'Rah", split = 566.4, fast = 498.6, slow = 637.6, runs = 18 },
					[3286] = { order = 2, name = "Atroxus", split = 945.7, fast = 899.8, slow = 1075.5, runs = 18 },
					[3287] = { order = 3, name = "Charonus", split = 1610.8, fast = 1530.5, slow = 1669.1, runs = 18 },
				},
				[12] = {
					[3285] = { order = 1, name = "Taz'Rah", split = 549.2, fast = 504.9, slow = 609.2, runs = 44 },
					[3286] = { order = 2, name = "Atroxus", split = 940.2, fast = 871.6, slow = 1015.4, runs = 45 },
					[3287] = { order = 3, name = "Charonus", split = 1470.6, fast = 1370.2, slow = 1625.3, runs = 45 },
				},
				[13] = {
					[3285] = { order = 1, name = "Taz'Rah", split = 584.7, fast = 537.8, slow = 614.3, runs = 11 },
					[3286] = { order = 2, name = "Atroxus", split = 1009.7, fast = 915.7, slow = 1053.1, runs = 11 },
					[3287] = { order = 3, name = "Charonus", split = 1600.1, fast = 1477.5, slow = 1657.2, runs = 11 },
				},
				[14] = {
					[3285] = { order = 1, name = "Taz'Rah", split = 571.6, fast = 530.7, slow = 588.5, runs = 9 },
					[3286] = { order = 2, name = "Atroxus", split = 970.5, fast = 922.6, slow = 1004.8, runs = 9 },
					[3287] = { order = 3, name = "Charonus", split = 1511.2, fast = 1457.7, slow = 1670.7, runs = 9 },
				},
				[15] = {
					[3285] = { order = 1, name = "Taz'Rah", split = 580.8, fast = 544.9, slow = 638.3, runs = 9 },
					[3286] = { order = 2, name = "Atroxus", split = 1009.9, fast = 955.1, slow = 1066.4, runs = 9 },
					[3287] = { order = 3, name = "Charonus", split = 1613.7, fast = 1460.3, slow = 1714.5, runs = 9 },
				},
			},
		},
		[586] = {
			name = "Den of Nalorakk",
			levels = {
				[2] = {
					[3207] = { order = 1, name = "The Hoardmonger", split = 431.4, fast = 366.1, slow = 450.9, runs = 8 },
					[3208] = { order = 2, name = "Sentinel of Winter", split = 914.0, fast = 791.4, slow = 948.1, runs = 8 },
					[3209] = { order = 3, name = "Nalorakk", split = 1298.2, fast = 1116.5, slow = 1324.4, runs = 8 },
				},
				[7] = {
					[3207] = { order = 1, name = "The Hoardmonger", split = 545.3, fast = 471.7, slow = 549.1, runs = 5 },
					[3208] = { order = 2, name = "Sentinel of Winter", split = 1049.9, fast = 963.0, slow = 1065.3, runs = 5 },
					[3209] = { order = 3, name = "Nalorakk", split = 1513.0, fast = 1390.7, slow = 1513.8, runs = 5 },
				},
				[8] = {
					[3207] = { order = 1, name = "The Hoardmonger", split = 545.5, fast = 508.3, slow = 616.7, runs = 11 },
					[3208] = { order = 2, name = "Sentinel of Winter", split = 1260.8, fast = 1172.4, slow = 1282.4, runs = 11 },
					[3209] = { order = 3, name = "Nalorakk", split = 1762.0, fast = 1635.2, slow = 1796.3, runs = 11 },
				},
				[9] = {
					[3207] = { order = 1, name = "The Hoardmonger", split = 492.8, fast = 473.0, slow = 525.2, runs = 8 },
					[3208] = { order = 2, name = "Sentinel of Winter", split = 1040.2, fast = 965.4, slow = 1100.2, runs = 9 },
					[3209] = { order = 3, name = "Nalorakk", split = 1526.9, fast = 1408.5, slow = 1590.9, runs = 9 },
				},
				[10] = {
					[3207] = { order = 1, name = "The Hoardmonger", split = 518.2, fast = 466.8, slow = 569.4, runs = 79 },
					[3208] = { order = 2, name = "Sentinel of Winter", split = 1099.4, fast = 998.0, slow = 1220.4, runs = 80 },
					[3209] = { order = 3, name = "Nalorakk", split = 1580.0, fast = 1443.5, slow = 1743.1, runs = 81 },
				},
				[11] = {
					[3207] = { order = 1, name = "The Hoardmonger", split = 531.1, fast = 477.9, slow = 650.2, runs = 17 },
					[3208] = { order = 2, name = "Sentinel of Winter", split = 1152.3, fast = 1009.4, slow = 1371.8, runs = 19 },
					[3209] = { order = 3, name = "Nalorakk", split = 1748.9, fast = 1478.4, slow = 2009.1, runs = 19 },
				},
				[12] = {
					[3207] = { order = 1, name = "The Hoardmonger", split = 526.1, fast = 471.7, slow = 582.2, runs = 47 },
					[3208] = { order = 2, name = "Sentinel of Winter", split = 1115.5, fast = 1053.4, slow = 1227.6, runs = 47 },
					[3209] = { order = 3, name = "Nalorakk", split = 1631.5, fast = 1511.0, slow = 1774.9, runs = 47 },
				},
				[13] = {
					[3207] = { order = 1, name = "The Hoardmonger", split = 548.8, fast = 508.5, slow = 582.7, runs = 12 },
					[3208] = { order = 2, name = "Sentinel of Winter", split = 1146.2, fast = 1097.2, slow = 1193.7, runs = 12 },
					[3209] = { order = 3, name = "Nalorakk", split = 1651.8, fast = 1600.6, slow = 1720.9, runs = 12 },
				},
				[14] = {
					[3207] = { order = 1, name = "The Hoardmonger", split = 555.4, fast = 518.9, slow = 626.8, runs = 13 },
					[3208] = { order = 2, name = "Sentinel of Winter", split = 1160.2, fast = 1102.5, slow = 1238.6, runs = 13 },
					[3209] = { order = 3, name = "Nalorakk", split = 1689.9, fast = 1653.0, slow = 1774.2, runs = 13 },
				},
				[15] = {
					[3207] = { order = 1, name = "The Hoardmonger", split = 547.7, fast = 495.8, slow = 582.2, runs = 13 },
					[3208] = { order = 2, name = "Sentinel of Winter", split = 1199.9, fast = 1130.7, slow = 1255.1, runs = 13 },
					[3209] = { order = 3, name = "Nalorakk", split = 1719.4, fast = 1675.4, slow = 1797.0, runs = 13 },
				},
			},
		},
		[587] = {
			name = "Murder Row",
			levels = {
				[2] = {
					[3101] = { order = 0, name = "Kystia Manaheart", split = 380.3, fast = 356.2, slow = 416.9, runs = 5 },
					[3102] = { order = 1, name = "Zaen Bladesorrow", split = 594.8, fast = 588.7, slow = 673.2, runs = 5 },
					[3103] = { order = 3, name = "Xathuux the Annihilator", split = 924.4, fast = 854.8, slow = 947.3, runs = 5 },
					[3105] = { order = 4, name = "Lithiel Cinderfury", split = 1239.3, fast = 1213.8, slow = 1292.0, runs = 5 },
				},
				[6] = {
					[3101] = { order = 0, name = "Kystia Manaheart", split = 322.1, fast = 312.5, slow = 327.6, runs = 5 },
					[3102] = { order = 1, name = "Zaen Bladesorrow", split = 534.7, fast = 529.2, slow = 542.3, runs = 5 },
					[3103] = { order = 3, name = "Xathuux the Annihilator", split = 820.3, fast = 815.9, slow = 832.0, runs = 5 },
					[3105] = { order = 4, name = "Lithiel Cinderfury", split = 1156.4, fast = 1111.6, slow = 1236.1, runs = 5 },
				},
				[7] = {
					[3101] = { order = 0, name = "Kystia Manaheart", split = 499.2, fast = 486.0, slow = 549.9, runs = 7 },
					[3102] = { order = 1, name = "Zaen Bladesorrow", split = 766.9, fast = 759.9, slow = 848.3, runs = 7 },
					[3103] = { order = 3, name = "Xathuux the Annihilator", split = 1181.0, fast = 1145.0, slow = 1261.7, runs = 7 },
					[3105] = { order = 4, name = "Lithiel Cinderfury", split = 1715.2, fast = 1610.3, slow = 1858.0, runs = 7 },
				},
				[8] = {
					[3101] = { order = 0, name = "Kystia Manaheart", split = 414.9, fast = 396.6, slow = 448.0, runs = 8 },
					[3102] = { order = 1, name = "Zaen Bladesorrow", split = 635.4, fast = 602.2, slow = 680.2, runs = 8 },
					[3103] = { order = 3, name = "Xathuux the Annihilator", split = 965.9, fast = 899.9, slow = 1054.8, runs = 8 },
					[3105] = { order = 4, name = "Lithiel Cinderfury", split = 1371.6, fast = 1242.0, slow = 1470.5, runs = 8 },
				},
				[9] = {
					[3101] = { order = 0, name = "Kystia Manaheart", split = 465.7, fast = 397.5, slow = 527.3, runs = 18 },
					[3102] = { order = 1, name = "Zaen Bladesorrow", split = 714.8, fast = 619.4, slow = 816.8, runs = 18 },
					[3103] = { order = 3, name = "Xathuux the Annihilator", split = 1104.0, fast = 976.4, slow = 1232.6, runs = 18 },
					[3105] = { order = 4, name = "Lithiel Cinderfury", split = 1497.4, fast = 1378.9, slow = 1745.2, runs = 18 },
				},
				[10] = {
					[3101] = { order = 0, name = "Kystia Manaheart", split = 446.9, fast = 399.0, slow = 525.6, runs = 100 },
					[3102] = { order = 1, name = "Zaen Bladesorrow", split = 717.1, fast = 648.2, slow = 832.7, runs = 100 },
					[3103] = { order = 3, name = "Xathuux the Annihilator", split = 1113.3, fast = 999.0, slow = 1271.4, runs = 100 },
					[3105] = { order = 4, name = "Lithiel Cinderfury", split = 1576.3, fast = 1385.2, slow = 1784.3, runs = 100 },
				},
				[11] = {
					[3101] = { order = 0, name = "Kystia Manaheart", split = 464.2, fast = 423.6, slow = 537.5, runs = 40 },
					[3102] = { order = 1, name = "Zaen Bladesorrow", split = 739.4, fast = 681.0, slow = 834.3, runs = 40 },
					[3103] = { order = 3, name = "Xathuux the Annihilator", split = 1149.2, fast = 1021.1, slow = 1306.0, runs = 40 },
					[3105] = { order = 4, name = "Lithiel Cinderfury", split = 1618.0, fast = 1416.5, slow = 1842.8, runs = 41 },
				},
				[12] = {
					[3101] = { order = 0, name = "Kystia Manaheart", split = 462.7, fast = 412.2, slow = 520.5, runs = 52 },
					[3102] = { order = 1, name = "Zaen Bladesorrow", split = 732.4, fast = 675.0, slow = 799.8, runs = 53 },
					[3103] = { order = 3, name = "Xathuux the Annihilator", split = 1148.6, fast = 1075.1, slow = 1241.2, runs = 53 },
					[3105] = { order = 4, name = "Lithiel Cinderfury", split = 1651.0, fast = 1557.8, slow = 1780.1, runs = 53 },
				},
				[13] = {
					[3101] = { order = 0, name = "Kystia Manaheart", split = 465.5, fast = 443.4, slow = 511.5, runs = 14 },
					[3102] = { order = 1, name = "Zaen Bladesorrow", split = 763.4, fast = 720.5, slow = 842.3, runs = 14 },
					[3103] = { order = 3, name = "Xathuux the Annihilator", split = 1268.3, fast = 1145.5, slow = 1365.3, runs = 14 },
					[3105] = { order = 4, name = "Lithiel Cinderfury", split = 1851.4, fast = 1663.0, slow = 1988.1, runs = 14 },
				},
				[14] = {
					[3101] = { order = 0, name = "Kystia Manaheart", split = 496.2, fast = 473.3, slow = 543.5, runs = 18 },
					[3102] = { order = 1, name = "Zaen Bladesorrow", split = 777.3, fast = 745.4, slow = 898.3, runs = 18 },
					[3103] = { order = 3, name = "Xathuux the Annihilator", split = 1269.5, fast = 1217.3, slow = 1408.6, runs = 18 },
					[3105] = { order = 4, name = "Lithiel Cinderfury", split = 1846.5, fast = 1672.1, slow = 1970.5, runs = 18 },
				},
				[15] = {
					[3101] = { order = 0, name = "Kystia Manaheart", split = 495.6, fast = 482.6, slow = 510.1, runs = 8 },
					[3102] = { order = 1, name = "Zaen Bladesorrow", split = 781.0, fast = 770.8, slow = 836.3, runs = 8 },
					[3103] = { order = 3, name = "Xathuux the Annihilator", split = 1294.5, fast = 1255.6, slow = 1338.4, runs = 8 },
					[3105] = { order = 4, name = "Lithiel Cinderfury", split = 1861.6, fast = 1779.9, slow = 1896.5, runs = 8 },
				},
				[16] = {
					[3101] = { order = 0, name = "Kystia Manaheart", split = 522.5, fast = 477.2, slow = 523.2, runs = 7 },
					[3102] = { order = 1, name = "Zaen Bladesorrow", split = 787.6, fast = 758.8, slow = 824.0, runs = 7 },
					[3103] = { order = 3, name = "Xathuux the Annihilator", split = 1278.4, fast = 1256.3, slow = 1328.9, runs = 7 },
					[3105] = { order = 4, name = "Lithiel Cinderfury", split = 1883.3, fast = 1783.5, slow = 1900.9, runs = 7 },
				},
			},
		},
		[588] = {
			name = "Altar of Fangs",
			levels = {
				[5] = {
					[3456] = { order = 1, name = "Rav'i", split = 441.6, fast = 398.3, slow = 465.9, runs = 6 },
					[3457] = { order = 2, name = "The Writhing Coil", split = 719.5, fast = 653.3, slow = 778.5, runs = 6 },
					[3458] = { order = 3, name = "Zul'jan", split = 1149.2, fast = 1055.9, slow = 1254.3, runs = 6 },
				},
				[6] = {
					[3456] = { order = 1, name = "Rav'i", split = 511.1, fast = 434.7, slow = 524.4, runs = 9 },
					[3457] = { order = 2, name = "The Writhing Coil", split = 818.0, fast = 740.8, slow = 863.0, runs = 9 },
					[3458] = { order = 3, name = "Zul'jan", split = 1314.7, fast = 1160.4, slow = 1391.4, runs = 9 },
				},
				[7] = {
					[3456] = { order = 1, name = "Rav'i", split = 466.4, fast = 410.2, slow = 494.4, runs = 5 },
					[3457] = { order = 2, name = "The Writhing Coil", split = 752.2, fast = 688.4, slow = 842.5, runs = 5 },
					[3458] = { order = 3, name = "Zul'jan", split = 1201.5, fast = 1130.0, slow = 1354.4, runs = 5 },
				},
				[8] = {
					[3456] = { order = 1, name = "Rav'i", split = 510.6, fast = 468.7, slow = 551.7, runs = 10 },
					[3457] = { order = 2, name = "The Writhing Coil", split = 842.9, fast = 795.0, slow = 909.5, runs = 10 },
					[3458] = { order = 3, name = "Zul'jan", split = 1364.6, fast = 1321.0, slow = 1480.2, runs = 10 },
				},
				[9] = {
					[3456] = { order = 1, name = "Rav'i", split = 539.8, fast = 477.2, slow = 559.2, runs = 10 },
					[3457] = { order = 2, name = "The Writhing Coil", split = 863.4, fast = 834.9, slow = 904.7, runs = 10 },
					[3458] = { order = 3, name = "Zul'jan", split = 1372.6, fast = 1339.3, slow = 1415.3, runs = 10 },
				},
				[10] = {
					[3456] = { order = 1, name = "Rav'i", split = 560.9, fast = 512.7, slow = 634.7, runs = 73 },
					[3457] = { order = 2, name = "The Writhing Coil", split = 945.4, fast = 855.7, slow = 1073.7, runs = 73 },
					[3458] = { order = 3, name = "Zul'jan", split = 1500.7, fast = 1377.3, slow = 1684.8, runs = 73 },
				},
				[11] = {
					[3456] = { order = 1, name = "Rav'i", split = 575.0, fast = 553.5, slow = 627.2, runs = 25 },
					[3457] = { order = 2, name = "The Writhing Coil", split = 961.9, fast = 921.5, slow = 1034.5, runs = 25 },
					[3458] = { order = 3, name = "Zul'jan", split = 1531.3, fast = 1426.7, slow = 1659.8, runs = 26 },
				},
				[12] = {
					[3456] = { order = 1, name = "Rav'i", split = 593.0, fast = 565.5, slow = 680.9, runs = 52 },
					[3457] = { order = 2, name = "The Writhing Coil", split = 1013.7, fast = 934.2, slow = 1096.5, runs = 52 },
					[3458] = { order = 3, name = "Zul'jan", split = 1581.2, fast = 1477.4, slow = 1688.2, runs = 52 },
				},
				[13] = {
					[3456] = { order = 1, name = "Rav'i", split = 622.9, fast = 590.4, slow = 667.0, runs = 23 },
					[3457] = { order = 2, name = "The Writhing Coil", split = 1020.5, fast = 988.0, slow = 1085.0, runs = 23 },
					[3458] = { order = 3, name = "Zul'jan", split = 1646.1, fast = 1592.4, slow = 1717.9, runs = 23 },
				},
				[14] = {
					[3456] = { order = 1, name = "Rav'i", split = 654.5, fast = 619.1, slow = 680.6, runs = 18 },
					[3457] = { order = 2, name = "The Writhing Coil", split = 1068.7, fast = 1030.5, slow = 1124.3, runs = 18 },
					[3458] = { order = 3, name = "Zul'jan", split = 1712.3, fast = 1612.1, slow = 1782.3, runs = 18 },
				},
				[15] = {
					[3456] = { order = 1, name = "Rav'i", split = 666.6, fast = 620.9, slow = 702.1, runs = 20 },
					[3457] = { order = 2, name = "The Writhing Coil", split = 1092.6, fast = 1051.6, slow = 1155.5, runs = 20 },
					[3458] = { order = 3, name = "Zul'jan", split = 1737.4, fast = 1664.2, slow = 1817.8, runs = 20 },
				},
				[16] = {
					[3456] = { order = 1, name = "Rav'i", split = 654.7, fast = 651.9, slow = 683.7, runs = 6 },
					[3457] = { order = 2, name = "The Writhing Coil", split = 1091.3, fast = 1076.5, slow = 1125.2, runs = 6 },
					[3458] = { order = 3, name = "Zul'jan", split = 1721.4, fast = 1689.3, slow = 1767.8, runs = 6 },
				},
			},
		},
	},
}
